// Generated by api_sync update from api/bindings.json. Do not edit.
// Only reviewed native bindings are declared here. See api/reaper_api.json for the catalogue.
interface ReaWebAPI {
  /** compatible.  */
  APIExists(function_name: string): Promise<boolean>;
  /** compatible.  */
  APITest(): Promise<void>;
  /** compatible.  */
  AddMediaItemToTrack(tr: MediaTrackHandle): Promise<MediaItemHandle | null>;
  /** compatible.  */
  AddProjectMarker(proj: ReaProjectHandle | null | 0, isrgn: boolean, pos: number, rgnend: number, name: string, wantidx: number): Promise<number>;
  /** compatible.  */
  AddProjectMarker2(proj: ReaProjectHandle | null | 0, isrgn: boolean, pos: number, rgnend: number, name: string, wantidx: number, color: number): Promise<number>;
  /** compatible.  */
  AddRegionOrMarker(proj: ReaProjectHandle | null | 0, isrgn: boolean, pos: number, rgnend: number, name: string, wantidx: number, color: number): Promise<ProjectMarkerHandle | null>;
  /** compatible.  */
  AddRemoveReaScript(add: boolean, sectionID: number, scriptfn: string, commit: boolean): Promise<number>;
  /** compatible.  */
  AddTakeToMediaItem(item: MediaItemHandle): Promise<MediaItem_TakeHandle | null>;
  /** compatible.  */
  AddTempoTimeSigMarker(proj: ReaProjectHandle | null | 0, timepos: number, bpm: number, timesig_num: number, timesig_denom: number, lineartempochange: boolean): Promise<boolean>;
  /** compatible.  */
  AnyTrackSolo(proj: ReaProjectHandle | null | 0): Promise<boolean>;
  /** compatible.  */
  ApplyNudge(project: ReaProjectHandle | null | 0, nudgeflag: number, nudgewhat: number, nudgeunits: number, value: number, reverse: boolean, copies: number): Promise<boolean>;
  /** compatible.  */
  ArmCommand(cmd: number, sectionname: string): Promise<void>;
  /** compatible.  */
  AudioAccessorStateChanged(accessor: AudioAccessorHandle): Promise<boolean>;
  /** compatible.  */
  AudioAccessorUpdate(accessor: AudioAccessorHandle): Promise<void>;
  /** compatible.  */
  AudioAccessorValidateState(accessor: AudioAccessorHandle): Promise<boolean>;
  /** compatible.  */
  Audio_Init(): Promise<void>;
  /** compatible.  */
  Audio_IsPreBuffer(): Promise<number>;
  /** compatible.  */
  Audio_IsRunning(): Promise<number>;
  /** compatible.  */
  Audio_Quit(): Promise<void>;
  /** compatible.  */
  BypassFxAllTracks(bypass: number): Promise<void>;
  /** compatible.  */
  CSurf_FlushUndo(force: boolean): Promise<void>;
  /** compatible.  */
  CSurf_GetTouchState(trackid: MediaTrackHandle, isPan: number): Promise<boolean>;
  /** compatible.  */
  CSurf_GoEnd(): Promise<void>;
  /** compatible.  */
  CSurf_GoStart(): Promise<void>;
  /** compatible.  */
  CSurf_NumTracks(mcpView: boolean): Promise<number>;
  /** compatible.  */
  CSurf_OnArrow(whichdir: number, wantzoom: boolean): Promise<void>;
  /** compatible.  */
  CSurf_OnFXChange(trackid: MediaTrackHandle, en: number): Promise<boolean>;
  /** compatible.  */
  CSurf_OnFwd(seekplay: number): Promise<void>;
  /** compatible.  */
  CSurf_OnInputMonitorChange(trackid: MediaTrackHandle, monitor: number): Promise<number>;
  /** compatible.  */
  CSurf_OnInputMonitorChangeEx(trackid: MediaTrackHandle, monitor: number, allowgang: boolean): Promise<number>;
  /** compatible.  */
  CSurf_OnMuteChange(trackid: MediaTrackHandle, mute: number): Promise<boolean>;
  /** compatible.  */
  CSurf_OnMuteChangeEx(trackid: MediaTrackHandle, mute: number, allowgang: boolean): Promise<boolean>;
  /** compatible.  */
  CSurf_OnPanChange(trackid: MediaTrackHandle, pan: number, relative: boolean): Promise<number>;
  /** compatible.  */
  CSurf_OnPanChangeEx(trackid: MediaTrackHandle, pan: number, relative: boolean, allowGang: boolean): Promise<number>;
  /** compatible.  */
  CSurf_OnPause(): Promise<void>;
  /** compatible.  */
  CSurf_OnPlay(): Promise<void>;
  /** compatible.  */
  CSurf_OnPlayRateChange(playrate: number): Promise<void>;
  /** compatible.  */
  CSurf_OnRecArmChange(trackid: MediaTrackHandle, recarm: number): Promise<boolean>;
  /** compatible.  */
  CSurf_OnRecArmChangeEx(trackid: MediaTrackHandle, recarm: number, allowgang: boolean): Promise<boolean>;
  /** compatible.  */
  CSurf_OnRecord(): Promise<void>;
  /** compatible.  */
  CSurf_OnRecvPanChange(trackid: MediaTrackHandle, recv_index: number, pan: number, relative: boolean): Promise<number>;
  /** compatible.  */
  CSurf_OnRecvVolumeChange(trackid: MediaTrackHandle, recv_index: number, volume: number, relative: boolean): Promise<number>;
  /** compatible.  */
  CSurf_OnRew(seekplay: number): Promise<void>;
  /** compatible.  */
  CSurf_OnRewFwd(seekplay: number, dir: number): Promise<void>;
  /** compatible.  */
  CSurf_OnScroll(xdir: number, ydir: number): Promise<void>;
  /** compatible.  */
  CSurf_OnSelectedChange(trackid: MediaTrackHandle, selected: number): Promise<boolean>;
  /** compatible.  */
  CSurf_OnSendPanChange(trackid: MediaTrackHandle, send_index: number, pan: number, relative: boolean): Promise<number>;
  /** compatible.  */
  CSurf_OnSendVolumeChange(trackid: MediaTrackHandle, send_index: number, volume: number, relative: boolean): Promise<number>;
  /** compatible.  */
  CSurf_OnSoloChange(trackid: MediaTrackHandle, solo: number): Promise<boolean>;
  /** compatible.  */
  CSurf_OnSoloChangeEx(trackid: MediaTrackHandle, solo: number, allowgang: boolean): Promise<boolean>;
  /** compatible.  */
  CSurf_OnStop(): Promise<void>;
  /** compatible.  */
  CSurf_OnTempoChange(bpm: number): Promise<void>;
  /** compatible.  */
  CSurf_OnTrackSelection(trackid: MediaTrackHandle): Promise<void>;
  /** compatible.  */
  CSurf_OnVolumeChange(trackid: MediaTrackHandle, volume: number, relative: boolean): Promise<number>;
  /** compatible.  */
  CSurf_OnVolumeChangeEx(trackid: MediaTrackHandle, volume: number, relative: boolean, allowGang: boolean): Promise<number>;
  /** compatible.  */
  CSurf_OnWidthChange(trackid: MediaTrackHandle, width: number, relative: boolean): Promise<number>;
  /** compatible.  */
  CSurf_OnWidthChangeEx(trackid: MediaTrackHandle, width: number, relative: boolean, allowGang: boolean): Promise<number>;
  /** compatible.  */
  CSurf_OnZoom(xdir: number, ydir: number): Promise<void>;
  /** compatible.  */
  CSurf_ResetAllCachedVolPanStates(): Promise<void>;
  /** compatible.  */
  CSurf_ScrubAmt(amt: number): Promise<void>;
  /** compatible.  */
  CSurf_SetAutoMode(mode: number, ignoresurf: IReaperControlSurfaceHandle | null): Promise<void>;
  /** compatible.  */
  CSurf_SetPlayState(play: boolean, pause: boolean, rec: boolean, ignoresurf: IReaperControlSurfaceHandle | null): Promise<void>;
  /** compatible.  */
  CSurf_SetRepeatState(rep: boolean, ignoresurf: IReaperControlSurfaceHandle | null): Promise<void>;
  /** compatible.  */
  CSurf_SetSurfaceMute(trackid: MediaTrackHandle, mute: boolean, ignoresurf: IReaperControlSurfaceHandle | null): Promise<void>;
  /** compatible.  */
  CSurf_SetSurfacePan(trackid: MediaTrackHandle, pan: number, ignoresurf: IReaperControlSurfaceHandle | null): Promise<void>;
  /** compatible.  */
  CSurf_SetSurfaceRecArm(trackid: MediaTrackHandle, recarm: boolean, ignoresurf: IReaperControlSurfaceHandle | null): Promise<void>;
  /** compatible.  */
  CSurf_SetSurfaceSelected(trackid: MediaTrackHandle, selected: boolean, ignoresurf: IReaperControlSurfaceHandle | null): Promise<void>;
  /** compatible.  */
  CSurf_SetSurfaceSolo(trackid: MediaTrackHandle, solo: boolean, ignoresurf: IReaperControlSurfaceHandle | null): Promise<void>;
  /** compatible.  */
  CSurf_SetSurfaceVolume(trackid: MediaTrackHandle, volume: number, ignoresurf: IReaperControlSurfaceHandle | null): Promise<void>;
  /** compatible.  */
  CSurf_SetTrackListChange(): Promise<void>;
  /** compatible.  */
  CSurf_TrackFromID(idx: number, mcpView: boolean): Promise<MediaTrackHandle | null>;
  /** compatible.  */
  CSurf_TrackToID(track: MediaTrackHandle, mcpView: boolean): Promise<number>;
  /** compatible.  */
  CalcMediaSrcLoudness(mediasource: PCM_sourceHandle): Promise<number>;
  /** compatible.  */
  CalculateNormalization(source: PCM_sourceHandle, normalizeTo: number, normalizeTarget: number, normalizeStart: number, normalizeEnd: number): Promise<number>;
  /** compatible.  */
  ClearAllRecArmed(): Promise<void>;
  /** compatible.  */
  ClearConsole(): Promise<void>;
  /** compatible.  */
  ClearPeakCache(): Promise<void>;
  /** compatible.  */
  ColorFromNative(col: number): Promise<[number, number, number]>;
  /** compatible.  */
  ColorToNative(r: number, g: number, b: number): Promise<number>;
  /** compatible.  */
  CountActionShortcuts(section: KbdSectionInfoHandle | null | 0, cmdID: number): Promise<number>;
  /** compatible.  */
  CountAutomationItems(env: TrackEnvelopeHandle): Promise<number>;
  /** compatible.  */
  CountEnvelopePoints(envelope: TrackEnvelopeHandle): Promise<number>;
  /** compatible.  */
  CountEnvelopePointsEx(envelope: TrackEnvelopeHandle, autoitem_idx: number): Promise<number>;
  /** compatible.  */
  CountMediaItems(proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  CountProjectMarkers(proj: ReaProjectHandle | null | 0): Promise<[number, number, number]>;
  /** compatible.  */
  CountSelectedMediaItems(proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  CountSelectedTracks(proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  CountSelectedTracks2(proj: ReaProjectHandle | null | 0, wantmaster: boolean): Promise<number>;
  /** compatible.  */
  CountTCPFXParms(project: ReaProjectHandle | null | 0, track: MediaTrackHandle): Promise<number>;
  /** compatible.  */
  CountTakeEnvelopes(take: MediaItem_TakeHandle): Promise<number>;
  /** compatible.  */
  CountTakes(item: MediaItemHandle): Promise<number>;
  /** compatible.  */
  CountTempoTimeSigMarkers(proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  CountTrackEnvelopes(track: MediaTrackHandle): Promise<number>;
  /** compatible.  */
  CountTrackMediaItems(track: MediaTrackHandle): Promise<number>;
  /** compatible.  */
  CountTracks(proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  CreateNewMIDIItemInProj(track: MediaTrackHandle, starttime: number, endtime: number, qnIn?: boolean): Promise<MediaItemHandle | null>;
  /** compatible.  */
  CreateTakeAudioAccessor(take: MediaItem_TakeHandle): Promise<AudioAccessorHandle | null>;
  /** compatible.  */
  CreateTrackAudioAccessor(track: MediaTrackHandle): Promise<AudioAccessorHandle | null>;
  /** compatible.  */
  CreateTrackSend(tr: MediaTrackHandle, desttrIn: MediaTrackHandle): Promise<number>;
  /** compatible.  */
  CrossfadeEditor_OnCommand(command: number): Promise<void>;
  /** compatible.  */
  CrossfadeEditor_Show(show: boolean): Promise<void>;
  /** compatible.  */
  DB2SLIDER(x: number): Promise<number>;
  /** compatible.  */
  DeleteActionShortcut(section: KbdSectionInfoHandle | null | 0, cmdID: number, shortcutidx: number): Promise<boolean>;
  /** compatible.  */
  DeleteEnvelopePointEx(envelope: TrackEnvelopeHandle, autoitem_idx: number, ptidx: number): Promise<boolean>;
  /** compatible.  */
  DeleteEnvelopePointRange(envelope: TrackEnvelopeHandle, time_start: number, time_end: number): Promise<boolean>;
  /** compatible.  */
  DeleteEnvelopePointRangeEx(envelope: TrackEnvelopeHandle, autoitem_idx: number, time_start: number, time_end: number): Promise<boolean>;
  /** compatible.  */
  DeleteExtState(section: string, key: string, persist: boolean): Promise<void>;
  /** compatible.  */
  DeleteProjectMarker(proj: ReaProjectHandle | null | 0, markrgnindexnumber: number, isrgn: boolean): Promise<boolean>;
  /** compatible.  */
  DeleteProjectMarkerByIndex(proj: ReaProjectHandle | null | 0, markrgnidx: number): Promise<boolean>;
  /** compatible.  */
  DeleteTakeMarker(take: MediaItem_TakeHandle, idx: number): Promise<boolean>;
  /** compatible.  */
  DeleteTakeStretchMarkers(take: MediaItem_TakeHandle, idx: number, countIn?: number): Promise<number>;
  /** compatible.  */
  DeleteTempoTimeSigMarker(project: ReaProjectHandle | null | 0, markerindex: number): Promise<boolean>;
  /** compatible.  */
  DeleteTrack(tr: MediaTrackHandle): Promise<void>;
  /** compatible.  */
  DeleteTrackMediaItem(tr: MediaTrackHandle, it: MediaItemHandle): Promise<boolean>;
  /** compatible.  */
  DestroyAudioAccessor(accessor: AudioAccessorHandle): Promise<void>;
  /** compatible.  */
  DoActionShortcutDialog(hwnd: HWNDHandle | null, section: KbdSectionInfoHandle | null | 0, cmdID: number, shortcutidx: number): Promise<boolean>;
  /** compatible.  */
  DockGetPosition(whichDock: number): Promise<number>;
  /** compatible.  */
  DockIsChildOfDock(hwnd: HWNDHandle | null): Promise<[number, boolean]>;
  /** compatible.  */
  DockWindowActivate(hwnd: HWNDHandle | null): Promise<void>;
  /** compatible.  */
  DockWindowAdd(hwnd: HWNDHandle | null, name: string, pos: number, allowShow: boolean): Promise<void>;
  /** compatible.  */
  DockWindowAddEx(hwnd: HWNDHandle | null, name: string, identstr: string, allowShow: boolean): Promise<void>;
  /** compatible.  */
  DockWindowRefresh(): Promise<void>;
  /** compatible.  */
  DockWindowRefreshForHWND(hwnd: HWNDHandle | null): Promise<void>;
  /** compatible.  */
  DockWindowRemove(hwnd: HWNDHandle | null): Promise<void>;
  /** compatible.  */
  Dock_UpdateDockID(ident_str: string, whichDock: number): Promise<void>;
  /** compatible.  */
  EditTempoTimeSigMarker(project: ReaProjectHandle | null | 0, markerindex: number): Promise<boolean>;
  /** compatible.  */
  EnsureNotCompletelyOffscreen(r_left: number, r_top: number, r_right: number, r_bot: number): Promise<[number, number, number, number]>;
  /** compatible.  */
  EnumInstalledFX(index: number): Promise<[boolean, string | null, string | null]>;
  /** compatible.  */
  EnumPitchShiftModes(mode: number): Promise<[boolean, string | null]>;
  /** compatible.  */
  EnumPitchShiftSubModes(mode: number, submode: number): Promise<string | null>;
  /** compatible.  */
  EnumProjExtState(proj: ReaProjectHandle | null | 0, extname: string, idx: number): Promise<[boolean, string, string]>;
  /** compatible.  */
  EnumProjectMarkers(idx: number): Promise<[number, boolean, number, number, string | null, number]>;
  /** compatible.  */
  EnumProjectMarkers2(proj: ReaProjectHandle | null | 0, idx: number): Promise<[number, boolean, number, number, string | null, number]>;
  /** compatible.  */
  EnumProjectMarkers3(proj: ReaProjectHandle | null | 0, idx: number): Promise<[number, boolean, number, number, string | null, number, number]>;
  /** compatible.  */
  EnumProjects(idx: number): Promise<[ReaProjectHandle | null, string]>;
  /** compatible.  */
  EnumRegionRenderMatrix(proj: ReaProjectHandle | null | 0, regionindex: number, rendertrack: number): Promise<MediaTrackHandle | null>;
  /** compatible.  */
  EnumTrackMIDIProgramNames(track: number, programNumber: number, programName: string): Promise<[boolean, string]>;
  /** compatible.  */
  EnumTrackMIDIProgramNamesEx(proj: ReaProjectHandle | null | 0, track: MediaTrackHandle, programNumber: number, programName: string): Promise<[boolean, string]>;
  /** compatible.  */
  EnumerateFiles(path: string, fileindex: number): Promise<string | null>;
  /** compatible.  */
  EnumerateSubdirectories(path: string, subdirindex: number): Promise<string | null>;
  /** compatible.  */
  Envelope_Evaluate(envelope: TrackEnvelopeHandle, time: number, samplerate: number, samplesRequested: number): Promise<[number, number, number, number, number]>;
  /** compatible.  */
  Envelope_FormatValue(env: TrackEnvelopeHandle, value: number): Promise<string>;
  /** compatible.  */
  Envelope_GetParentTake(env: TrackEnvelopeHandle): Promise<[MediaItem_TakeHandle | null, number, number]>;
  /** compatible.  */
  Envelope_GetParentTrack(env: TrackEnvelopeHandle): Promise<[MediaTrackHandle | null, number, number]>;
  /** compatible.  */
  Envelope_SortPoints(envelope: TrackEnvelopeHandle): Promise<boolean>;
  /** compatible.  */
  Envelope_SortPointsEx(envelope: TrackEnvelopeHandle, autoitem_idx: number): Promise<boolean>;
  /** compatible.  */
  ExecProcess(cmdline: string, timeoutmsec: number): Promise<string | null>;
  /** compatible.  */
  FindTempoTimeSigMarker(project: ReaProjectHandle | null | 0, time: number): Promise<number>;
  /** compatible.  */
  GR_SelectColor(hwnd: HWNDHandle | null): Promise<[number, number]>;
  /** compatible.  */
  GSC_mainwnd(t: number): Promise<number>;
  /** compatible.  */
  GetActionShortcutDesc(section: KbdSectionInfoHandle | null | 0, cmdID: number, shortcutidx: number): Promise<[boolean, string]>;
  /** compatible.  */
  GetActiveTake(item: MediaItemHandle): Promise<MediaItem_TakeHandle | null>;
  /** compatible.  */
  GetAllProjectPlayStates(ignoreProject: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  GetAppVersion(): Promise<string | null>;
  /** compatible.  */
  GetArmedCommand(): Promise<[number, string]>;
  /** compatible.  */
  GetAudioAccessorEndTime(accessor: AudioAccessorHandle): Promise<number>;
  /** compatible.  */
  GetAudioAccessorHash(accessor: AudioAccessorHandle, hashNeed128: string): Promise<string>;
  /** compatible.  */
  GetAudioAccessorSamples(accessor: AudioAccessorHandle, samplerate: number, numchannels: number, starttime_sec: number, numsamplesperchannel: number, samplebuffer: Float64Array | number[]): Promise<number>;
  /** compatible.  */
  GetAudioAccessorStartTime(accessor: AudioAccessorHandle): Promise<number>;
  /** compatible.  */
  GetAudioDeviceInfo(attribute: string): Promise<[boolean, string]>;
  /** compatible.  */
  GetConfigWantsDock(ident_str: string): Promise<number>;
  /** compatible.  */
  GetCurrentProjectInLoadSave(): Promise<ReaProjectHandle | null>;
  /** compatible.  */
  GetCursorContext(): Promise<number>;
  /** compatible.  */
  GetCursorContext2(want_last_valid: boolean): Promise<number>;
  /** compatible.  */
  GetCursorPosition(): Promise<number>;
  /** compatible.  */
  GetCursorPositionEx(proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  GetDisplayedMediaItemColor(item: MediaItemHandle): Promise<number>;
  /** compatible.  */
  GetDisplayedMediaItemColor2(item: MediaItemHandle, take: MediaItem_TakeHandle): Promise<number>;
  /** compatible.  */
  GetEnvelopeInfo_Value(env: TrackEnvelopeHandle, parmname: string): Promise<number>;
  /** compatible.  */
  GetEnvelopeName(env: TrackEnvelopeHandle): Promise<[boolean, string]>;
  /** compatible.  */
  GetEnvelopePoint(envelope: TrackEnvelopeHandle, ptidx: number): Promise<[boolean, number, number, number, number, boolean]>;
  /** compatible.  */
  GetEnvelopePointByTime(envelope: TrackEnvelopeHandle, time: number): Promise<number>;
  /** compatible.  */
  GetEnvelopePointByTimeEx(envelope: TrackEnvelopeHandle, autoitem_idx: number, time: number): Promise<number>;
  /** compatible.  */
  GetEnvelopePointEx(envelope: TrackEnvelopeHandle, autoitem_idx: number, ptidx: number): Promise<[boolean, number, number, number, number, boolean]>;
  /** compatible.  */
  GetEnvelopeScalingMode(env: TrackEnvelopeHandle): Promise<number>;
  /** compatible.  */
  GetEnvelopeStateChunk(env: TrackEnvelopeHandle, str: string, isundo: boolean): Promise<[boolean, string]>;
  /** compatible.  */
  GetEnvelopeUIState(env: TrackEnvelopeHandle): Promise<number>;
  /** compatible.  */
  GetExePath(): Promise<string | null>;
  /** compatible.  */
  GetExtState(section: string, key: string): Promise<string | null>;
  /** compatible.  */
  GetFXEnvelope(track: MediaTrackHandle, fxindex: number, parameterindex: number, create: boolean): Promise<TrackEnvelopeHandle | null>;
  /** compatible.  */
  GetFocusedFX(): Promise<[number, number, number, number]>;
  /** compatible.  */
  GetFocusedFX2(): Promise<[number, number, number, number]>;
  /** compatible.  */
  GetFreeDiskSpaceForRecordPath(proj: ReaProjectHandle | null | 0, pathidx: number): Promise<number>;
  /** compatible.  */
  GetGlobalAutomationOverride(): Promise<number>;
  /** compatible.  */
  GetHZoomLevel(): Promise<number>;
  /** compatible.  */
  GetInputActivityLevel(input_id: number): Promise<number>;
  /** compatible.  */
  GetInputChannelName(channelIndex: number): Promise<string | null>;
  /** compatible.  */
  GetInputOutputLatency(): Promise<[number, number]>;
  /** compatible.  */
  GetItemEditingTime2(): Promise<[number, PCM_sourceHandle | null, number]>;
  /** compatible.  */
  GetItemFromPoint(screen_x: number, screen_y: number, allow_locked: boolean): Promise<[MediaItemHandle | null, MediaItem_TakeHandle | null]>;
  /** compatible.  */
  GetItemProjectContext(item: MediaItemHandle): Promise<ReaProjectHandle | null>;
  /** compatible.  */
  GetItemStateChunk(item: MediaItemHandle, str: string, isundo: boolean): Promise<[boolean, string]>;
  /** compatible.  */
  GetLastColorThemeFile(): Promise<string | null>;
  /** compatible.  */
  GetLastMarkerAndCurRegion(proj: ReaProjectHandle | null | 0, time: number): Promise<[number, number]>;
  /** compatible.  */
  GetLastTouchedFX(): Promise<[boolean, number, number, number]>;
  /** compatible.  */
  GetLastTouchedTrack(): Promise<MediaTrackHandle | null>;
  /** compatible.  */
  GetMIDIInputName(dev: number, nameout: string): Promise<[boolean, string]>;
  /** compatible.  */
  GetMIDIInputNameNoAlias(dev: number, nameout: string): Promise<[boolean, string]>;
  /** compatible.  */
  GetMIDIOutputName(dev: number, nameout: string): Promise<[boolean, string]>;
  /** compatible.  */
  GetMIDIOutputNameNoAlias(dev: number, nameout: string): Promise<[boolean, string]>;
  /** compatible.  */
  GetMainHwnd(): Promise<HWNDHandle | null>;
  /** compatible.  */
  GetMasterMuteSoloFlags(): Promise<number>;
  /** compatible.  */
  GetMasterTrack(proj: ReaProjectHandle | null | 0): Promise<MediaTrackHandle | null>;
  /** compatible.  */
  GetMasterTrackVisibility(): Promise<number>;
  /** compatible.  */
  GetMaxMidiInputs(): Promise<number>;
  /** compatible.  */
  GetMaxMidiOutputs(): Promise<number>;
  /** compatible.  */
  GetMediaFileMetadata(mediaSource: PCM_sourceHandle, identifier: string): Promise<[number, string]>;
  /** compatible.  */
  GetMediaItem(proj: ReaProjectHandle | null | 0, itemidx: number): Promise<MediaItemHandle | null>;
  /** compatible.  */
  GetMediaItemInfo_Value(item: MediaItemHandle, parmname: string): Promise<number>;
  /** compatible.  */
  GetMediaItemNumTakes(item: MediaItemHandle): Promise<number>;
  /** compatible.  */
  GetMediaItemTake(item: MediaItemHandle, tk: number): Promise<MediaItem_TakeHandle | null>;
  /** compatible.  */
  GetMediaItemTakeByGUID(project: ReaProjectHandle | null | 0, guidGUID: string): Promise<MediaItem_TakeHandle | null>;
  /** compatible.  */
  GetMediaItemTakeInfo_Value(take: MediaItem_TakeHandle, parmname: string): Promise<number>;
  /** compatible.  */
  GetMediaItemTake_Item(take: MediaItem_TakeHandle): Promise<MediaItemHandle | null>;
  /** compatible.  */
  GetMediaItemTake_Peaks(take: MediaItem_TakeHandle, peakrate: number, starttime: number, numchannels: number, numsamplesperchannel: number, want_extra_type: number, buf: Float64Array | number[]): Promise<number>;
  /** compatible.  */
  GetMediaItemTake_Source(take: MediaItem_TakeHandle): Promise<PCM_sourceHandle | null>;
  /** compatible.  */
  GetMediaItemTake_Track(take: MediaItem_TakeHandle): Promise<MediaTrackHandle | null>;
  /** compatible.  */
  GetMediaItemTrack(item: MediaItemHandle): Promise<MediaTrackHandle | null>;
  /** compatible.  */
  GetMediaItem_Track(item: MediaItemHandle): Promise<MediaTrackHandle | null>;
  /** compatible.  */
  GetMediaSourceFileName(source: PCM_sourceHandle): Promise<string>;
  /** compatible.  */
  GetMediaSourceLength(source: PCM_sourceHandle): Promise<[number, boolean]>;
  /** compatible.  */
  GetMediaSourceNumChannels(source: PCM_sourceHandle): Promise<number>;
  /** compatible.  */
  GetMediaSourceParent(src: PCM_sourceHandle): Promise<PCM_sourceHandle | null>;
  /** compatible.  */
  GetMediaSourceSampleRate(source: PCM_sourceHandle): Promise<number>;
  /** compatible.  */
  GetMediaSourceType(source: PCM_sourceHandle): Promise<string>;
  /** compatible.  */
  GetMediaTrackInfo_Value(tr: MediaTrackHandle, parmname: string): Promise<number>;
  /** compatible.  */
  GetMixerScroll(): Promise<MediaTrackHandle | null>;
  /** compatible.  */
  GetMouseModifier(context: string, modifier_flag: number): Promise<string>;
  /** compatible.  */
  GetMousePosition(): Promise<[number, number]>;
  /** compatible.  */
  GetNumAudioInputs(): Promise<number>;
  /** compatible.  */
  GetNumAudioOutputs(): Promise<number>;
  /** compatible.  */
  GetNumMIDIInputs(): Promise<number>;
  /** compatible.  */
  GetNumMIDIOutputs(): Promise<number>;
  /** compatible.  */
  GetNumRegionsOrMarkers(proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  GetNumTakeMarkers(take: MediaItem_TakeHandle): Promise<number>;
  /** compatible.  */
  GetNumTracks(): Promise<number>;
  /** compatible.  */
  GetOS(): Promise<string | null>;
  /** compatible.  */
  GetOutputChannelName(channelIndex: number): Promise<string | null>;
  /** compatible.  */
  GetOutputLatency(): Promise<number>;
  /** compatible.  */
  GetParentTrack(track: MediaTrackHandle): Promise<MediaTrackHandle | null>;
  /** compatible.  */
  GetPeakFileName(fn: string): Promise<string>;
  /** compatible.  */
  GetPeakFileNameEx(fn: string, buf: string, forWrite: boolean): Promise<string>;
  /** compatible.  */
  GetPeakFileNameEx2(fn: string, buf: string, forWrite: boolean, peaksfileextension: string): Promise<string>;
  /** compatible.  */
  GetPlayPosition(): Promise<number>;
  /** compatible.  */
  GetPlayPosition2(): Promise<number>;
  /** compatible.  */
  GetPlayPosition2Ex(proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  GetPlayPositionEx(proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  GetPlayState(): Promise<number>;
  /** compatible.  */
  GetPlayStateEx(proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  GetProjExtState(proj: ReaProjectHandle | null | 0, extname: string, key: string): Promise<[number, string]>;
  /** compatible.  */
  GetProjectLength(proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  GetProjectName(proj: ReaProjectHandle | null | 0): Promise<string>;
  /** compatible.  */
  GetProjectPath(): Promise<string>;
  /** compatible.  */
  GetProjectPathEx(proj: ReaProjectHandle | null | 0): Promise<string>;
  /** compatible.  */
  GetProjectStateChangeCount(proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  GetProjectTimeOffset(proj: ReaProjectHandle | null | 0, rndframe: boolean): Promise<number>;
  /** compatible.  */
  GetProjectTimeSignature(): Promise<[number, number]>;
  /** compatible.  */
  GetProjectTimeSignature2(proj: ReaProjectHandle | null | 0): Promise<[number, number]>;
  /** compatible.  */
  GetRegionOrMarker(proj: ReaProjectHandle | null | 0, index: number, guidStr: string): Promise<ProjectMarkerHandle | null>;
  /** compatible.  */
  GetRegionOrMarkerInfo_Value(proj: ReaProjectHandle | null | 0, regionOrMarker: ProjectMarkerHandle, parameterName: string): Promise<number>;
  /** compatible.  */
  GetResourcePath(): Promise<string | null>;
  /** compatible.  */
  GetSelectedEnvelope(proj: ReaProjectHandle | null | 0): Promise<TrackEnvelopeHandle | null>;
  /** compatible.  */
  GetSelectedMediaItem(proj: ReaProjectHandle | null | 0, selitem: number): Promise<MediaItemHandle | null>;
  /** compatible.  */
  GetSelectedTrack(proj: ReaProjectHandle | null | 0, seltrackidx: number): Promise<MediaTrackHandle | null>;
  /** compatible.  */
  GetSelectedTrack2(proj: ReaProjectHandle | null | 0, seltrackidx: number, wantmaster: boolean): Promise<MediaTrackHandle | null>;
  /** compatible.  */
  GetSelectedTrackEnvelope(proj: ReaProjectHandle | null | 0): Promise<TrackEnvelopeHandle | null>;
  /** compatible.  */
  GetSetAutomationItemInfo(env: TrackEnvelopeHandle, autoitem_idx: number, desc: string, value: number, is_set: boolean): Promise<number>;
  /** compatible.  */
  GetSetAutomationItemInfo_String(env: TrackEnvelopeHandle, autoitem_idx: number, desc: string, valuestrNeedBig: string, is_set: boolean): Promise<[boolean, string]>;
  /** compatible.  */
  GetSetEnvelopeInfo_String(env: TrackEnvelopeHandle, parmname: string, stringNeedBig: string, setNewValue: boolean): Promise<[boolean, string]>;
  /** compatible.  */
  GetSetEnvelopeState(env: TrackEnvelopeHandle, str: string): Promise<[boolean, string]>;
  /** compatible.  */
  GetSetEnvelopeState2(env: TrackEnvelopeHandle, str: string, isundo: boolean): Promise<[boolean, string]>;
  /** compatible.  */
  GetSetItemState(item: MediaItemHandle, str: string): Promise<[boolean, string]>;
  /** compatible.  */
  GetSetItemState2(item: MediaItemHandle, str: string, isundo: boolean): Promise<[boolean, string]>;
  /** compatible.  */
  GetSetMediaItemInfo_String(item: MediaItemHandle, parmname: string, stringNeedBig: string, setNewValue: boolean): Promise<[boolean, string]>;
  /** compatible.  */
  GetSetMediaItemTakeInfo_String(tk: MediaItem_TakeHandle, parmname: string, stringNeedBig: string, setNewValue: boolean): Promise<[boolean, string]>;
  /** compatible.  */
  GetSetMediaTrackInfo_String(tr: MediaTrackHandle, parmname: string, stringNeedBig: string, setNewValue: boolean): Promise<[boolean, string]>;
  /** compatible.  */
  GetSetProjectAuthor(proj: ReaProjectHandle | null | 0, set: boolean, author: string): Promise<string>;
  /** compatible.  */
  GetSetProjectGrid(project: ReaProjectHandle | null | 0, set: boolean, division?: number, swingmode?: number, swingamt?: number): Promise<[number, number, number, number]>;
  /** compatible.  */
  GetSetProjectInfo(project: ReaProjectHandle | null | 0, desc: string, value: number, is_set: boolean): Promise<number>;
  /** compatible.  */
  GetSetProjectInfo_String(project: ReaProjectHandle | null | 0, desc: string, valuestrNeedBig: string, is_set: boolean): Promise<[boolean, string]>;
  /** compatible.  */
  GetSetProjectNotes(proj: ReaProjectHandle | null | 0, set: boolean, notes: string): Promise<string>;
  /** compatible.  */
  GetSetRegionOrMarkerInfo_String(proj: ReaProjectHandle | null | 0, regionOrMarker: ProjectMarkerHandle, parameterName: string, stringNeedBig: string, setNewValue: boolean): Promise<[boolean, string]>;
  /** compatible.  */
  GetSetRepeat(val: number): Promise<number>;
  /** compatible.  */
  GetSetRepeatEx(proj: ReaProjectHandle | null | 0, val: number): Promise<number>;
  /** compatible.  */
  GetSetTempoTimeSigMarkerBasis(project: ReaProjectHandle | null | 0, point_index: number, beatbase: number, is_set: boolean): Promise<number>;
  /** compatible.  */
  GetSetTempoTimeSigMarkerFlag(project: ReaProjectHandle | null | 0, point_index: number, flag: number, is_set: boolean): Promise<number>;
  /** compatible.  */
  GetSetTrackGroupMembership(tr: MediaTrackHandle, groupname: string, setmask: number, setvalue: number): Promise<number>;
  /** compatible.  */
  GetSetTrackGroupMembershipEx(tr: MediaTrackHandle, groupname: string, offset: number, setmask: number, setvalue: number): Promise<number>;
  /** compatible.  */
  GetSetTrackGroupMembershipHigh(tr: MediaTrackHandle, groupname: string, setmask: number, setvalue: number): Promise<number>;
  /** compatible.  */
  GetSetTrackSendInfo_String(tr: MediaTrackHandle, category: number, sendidx: number, parmname: string, stringNeedBig: string, setNewValue: boolean): Promise<[boolean, string]>;
  /** compatible.  */
  GetSetTrackState(track: MediaTrackHandle, str: string): Promise<[boolean, string]>;
  /** compatible.  */
  GetSetTrackState2(track: MediaTrackHandle, str: string, isundo: boolean): Promise<[boolean, string]>;
  /** compatible.  */
  GetSet_ArrangeView2(proj: ReaProjectHandle | null | 0, isSet: boolean, screen_x_start: number, screen_x_end: number, start_time: number, end_time: number): Promise<[number, number]>;
  /** compatible.  */
  GetSet_LoopTimeRange(isSet: boolean, isLoop: boolean, start: number, end: number, allowautoseek: boolean): Promise<[number, number]>;
  /** compatible.  */
  GetSet_LoopTimeRange2(proj: ReaProjectHandle | null | 0, isSet: boolean, isLoop: boolean, start: number, end: number, allowautoseek: boolean): Promise<[number, number]>;
  /** compatible.  */
  GetSubProjectFromSource(src: PCM_sourceHandle): Promise<ReaProjectHandle | null>;
  /** compatible.  */
  GetTCPFXParm(project: ReaProjectHandle | null | 0, track: MediaTrackHandle, index: number): Promise<[boolean, number, number]>;
  /** compatible.  */
  GetTake(item: MediaItemHandle, takeidx: number): Promise<MediaItem_TakeHandle | null>;
  /** compatible.  */
  GetTakeEnvelope(take: MediaItem_TakeHandle, envidx: number): Promise<TrackEnvelopeHandle | null>;
  /** compatible.  */
  GetTakeEnvelopeByName(take: MediaItem_TakeHandle, envname: string): Promise<TrackEnvelopeHandle | null>;
  /** compatible.  */
  GetTakeMarker(take: MediaItem_TakeHandle, idx: number): Promise<[number, string, number]>;
  /** compatible.  */
  GetTakeName(take: MediaItem_TakeHandle | null): Promise<string | null>;
  /** compatible.  */
  GetTakeNumStretchMarkers(take: MediaItem_TakeHandle): Promise<number>;
  /** compatible.  */
  GetTakeStretchMarker(take: MediaItem_TakeHandle, idx: number): Promise<[number, number, number]>;
  /** compatible.  */
  GetTakeStretchMarkerSlope(take: MediaItem_TakeHandle, idx: number): Promise<number>;
  /** compatible.  */
  GetTempoMatchPlayRate(source: PCM_sourceHandle, srcscale: number, position: number, mult: number): Promise<[boolean, number, number]>;
  /** compatible.  */
  GetTempoTimeSigMarker(proj: ReaProjectHandle | null | 0, ptidx: number): Promise<[boolean, number, number, number, number, number, number, boolean]>;
  /** compatible.  */
  GetThemeColor(ini_key: string, flags: number): Promise<number>;
  /** compatible.  */
  GetThingFromPoint(screen_x: number, screen_y: number): Promise<[MediaTrackHandle | null, string]>;
  /** compatible.  */
  GetToggleCommandState(command_id: number): Promise<number>;
  /** compatible.  */
  GetToggleCommandStateEx(section_id: number, command_id: number): Promise<number>;
  /** compatible.  */
  GetTooltipWindow(): Promise<HWNDHandle | null>;
  /** compatible.  */
  GetTouchedOrFocusedFX(mode: number): Promise<[boolean, number, number, number, number, number]>;
  /** compatible.  */
  GetTrack(proj: ReaProjectHandle | null | 0, trackidx: number): Promise<MediaTrackHandle | null>;
  /** compatible.  */
  GetTrackAutomationMode(tr: MediaTrackHandle): Promise<number>;
  /** compatible.  */
  GetTrackColor(track: MediaTrackHandle): Promise<number>;
  /** compatible.  */
  GetTrackDepth(track: MediaTrackHandle): Promise<number>;
  /** compatible.  */
  GetTrackEnvelope(track: MediaTrackHandle, envidx: number): Promise<TrackEnvelopeHandle | null>;
  /** compatible.  */
  GetTrackEnvelopeByChunkName(tr: MediaTrackHandle, cfgchunkname_or_guid: string): Promise<TrackEnvelopeHandle | null>;
  /** compatible.  */
  GetTrackEnvelopeByName(track: MediaTrackHandle, envname: string): Promise<TrackEnvelopeHandle | null>;
  /** compatible.  */
  GetTrackFromPoint(screen_x: number, screen_y: number): Promise<[MediaTrackHandle | null, number]>;
  /** compatible.  */
  GetTrackGUID(tr: MediaTrackHandle): Promise<string | null>;
  /** compatible.  */
  GetTrackMIDILyrics(track: MediaTrackHandle, flag: number): Promise<[boolean, string]>;
  /** compatible.  */
  GetTrackMIDINoteName(track: number, pitch: number, chan: number): Promise<string | null>;
  /** compatible.  */
  GetTrackMIDINoteNameEx(proj: ReaProjectHandle | null | 0, track: MediaTrackHandle, pitch: number, chan: number): Promise<string | null>;
  /** compatible.  */
  GetTrackMIDINoteRange(proj: ReaProjectHandle | null | 0, track: MediaTrackHandle): Promise<[number, number]>;
  /** compatible.  */
  GetTrackMediaItem(tr: MediaTrackHandle, itemidx: number): Promise<MediaItemHandle | null>;
  /** compatible.  */
  GetTrackName(track: MediaTrackHandle): Promise<[boolean, string]>;
  /** compatible.  */
  GetTrackNumMediaItems(tr: MediaTrackHandle): Promise<number>;
  /** compatible.  */
  GetTrackNumSends(tr: MediaTrackHandle, category: number): Promise<number>;
  /** compatible.  */
  GetTrackReceiveName(track: MediaTrackHandle, recv_index: number): Promise<[boolean, string]>;
  /** compatible.  */
  GetTrackReceiveUIMute(track: MediaTrackHandle, recv_index: number): Promise<[boolean, boolean]>;
  /** compatible.  */
  GetTrackReceiveUIVolPan(track: MediaTrackHandle, recv_index: number): Promise<[boolean, number, number]>;
  /** compatible.  */
  GetTrackSendInfo_Value(tr: MediaTrackHandle, category: number, sendidx: number, parmname: string): Promise<number>;
  /** compatible.  */
  GetTrackSendName(track: MediaTrackHandle, send_index: number): Promise<[boolean, string]>;
  /** compatible.  */
  GetTrackSendUIMute(track: MediaTrackHandle, send_index: number): Promise<[boolean, boolean]>;
  /** compatible.  */
  GetTrackSendUIVolPan(track: MediaTrackHandle, send_index: number): Promise<[boolean, number, number]>;
  /** compatible.  */
  GetTrackState(track: MediaTrackHandle): Promise<[string | null, number]>;
  /** compatible.  */
  GetTrackStateChunk(track: MediaTrackHandle, str: string, isundo: boolean): Promise<[boolean, string]>;
  /** compatible.  */
  GetTrackUIMute(track: MediaTrackHandle): Promise<[boolean, boolean]>;
  /** compatible.  */
  GetTrackUIPan(track: MediaTrackHandle): Promise<[boolean, number, number, number]>;
  /** compatible.  */
  GetTrackUIVolPan(track: MediaTrackHandle): Promise<[boolean, number, number]>;
  /** compatible.  */
  GetUnderrunTime(): Promise<[number, number, number]>;
  /** compatible.  */
  GetUserFileName(mode: number, caption: string, initial_file_or_path: string, extension_list: string): Promise<[boolean, string]>;
  /** compatible.  */
  GetUserFileNameForRead(filenameNeed4096: string, title: string, defext: string): Promise<[boolean, string]>;
  /** compatible.  */
  GetUserInputs(title: string, num_inputs: number, captions_csv: string, retvals_csv: string): Promise<[boolean, string]>;
  /** compatible.  */
  GoToMarker(proj: ReaProjectHandle | null | 0, marker_index: number, use_timeline_order: boolean): Promise<void>;
  /** compatible.  */
  GoToRegion(proj: ReaProjectHandle | null | 0, region_index: number, use_timeline_order: boolean): Promise<void>;
  /** compatible.  */
  HasExtState(section: string, key: string): Promise<boolean>;
  /** compatible.  */
  HasTrackMIDIPrograms(track: number): Promise<string | null>;
  /** compatible.  */
  HasTrackMIDIProgramsEx(proj: ReaProjectHandle | null | 0, track: MediaTrackHandle): Promise<string | null>;
  /** compatible.  */
  Help_Set(helpstring: string, is_temporary_help: boolean): Promise<void>;
  /** compatible.  */
  InsertAutomationItem(env: TrackEnvelopeHandle, pool_id: number, position: number, length: number): Promise<number>;
  /** compatible.  */
  InsertEnvelopePoint(envelope: TrackEnvelopeHandle, time: number, value: number, shape: number, tension: number, selected: boolean, noSortIn?: boolean): Promise<boolean>;
  /** compatible.  */
  InsertEnvelopePointEx(envelope: TrackEnvelopeHandle, autoitem_idx: number, time: number, value: number, shape: number, tension: number, selected: boolean, noSortIn?: boolean): Promise<boolean>;
  /** compatible.  */
  InsertMedia(file: string, mode: number): Promise<number>;
  /** compatible.  */
  InsertMediaSection(file: string, mode: number, startpct: number, endpct: number, pitchshift: number): Promise<number>;
  /** compatible.  */
  InsertTrackAtIndex(idx: number, wantDefaults: boolean): Promise<void>;
  /** compatible.  */
  InsertTrackInProject(proj: ReaProjectHandle | null | 0, idx: number, flags: number): Promise<void>;
  /** compatible.  */
  IsMediaExtension(ext: string, wantOthers: boolean): Promise<boolean>;
  /** compatible.  */
  IsMediaItemSelected(item: MediaItemHandle): Promise<boolean>;
  /** compatible.  */
  IsProjectDirty(proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  IsTrackSelected(track: MediaTrackHandle): Promise<boolean>;
  /** compatible.  */
  IsTrackVisible(track: MediaTrackHandle, mixer: boolean): Promise<boolean>;
  /** compatible.  */
  LICE_ClipLine(pX1: number, pY1: number, pX2: number, pY2: number, xLo: number, yLo: number, xHi: number, yHi: number): Promise<[boolean, number, number, number, number]>;
  /** compatible.  */
  LocalizeString(src_string: string, section: string, flags: number): Promise<string | null>;
  /** compatible.  */
  Loop_OnArrow(project: ReaProjectHandle | null | 0, direction: number): Promise<boolean>;
  /** compatible.  */
  MB(msg: string, title: string, type: number): Promise<number>;
  /** compatible.  */
  MIDIEditorFlagsForTrack(track: MediaTrackHandle, pitchwheelrange: number, flags: number, is_set: boolean): Promise<[number, number]>;
  /** compatible.  */
  MIDIEditor_EnumTakes(midieditor: HWNDHandle | null, takeindex: number, editable_only: boolean): Promise<MediaItem_TakeHandle | null>;
  /** compatible.  */
  MIDIEditor_GetActive(): Promise<HWNDHandle | null>;
  /** compatible.  */
  MIDIEditor_GetMode(midieditor: HWNDHandle | null): Promise<number>;
  /** compatible.  */
  MIDIEditor_GetSetting_int(midieditor: HWNDHandle | null, setting_desc: string): Promise<number>;
  /** compatible.  */
  MIDIEditor_GetSetting_str(midieditor: HWNDHandle | null, setting_desc: string): Promise<[boolean, string]>;
  /** compatible.  */
  MIDIEditor_GetTake(midieditor: HWNDHandle | null): Promise<MediaItem_TakeHandle | null>;
  /** compatible.  */
  MIDIEditor_LastFocused_OnCommand(command_id: number, islistviewcommand: boolean): Promise<boolean>;
  /** compatible.  */
  MIDIEditor_OnCommand(midieditor: HWNDHandle | null, command_id: number): Promise<boolean>;
  /** compatible.  */
  MIDIEditor_SetSetting_int(midieditor: HWNDHandle | null, setting_desc: string, setting: number): Promise<boolean>;
  /** compatible.  */
  MIDI_CountEvts(take: MediaItem_TakeHandle): Promise<[number, number, number, number]>;
  /** compatible.  */
  MIDI_DeleteCC(take: MediaItem_TakeHandle, ccidx: number): Promise<boolean>;
  /** compatible.  */
  MIDI_DeleteEvt(take: MediaItem_TakeHandle, evtidx: number): Promise<boolean>;
  /** compatible.  */
  MIDI_DeleteNote(take: MediaItem_TakeHandle, noteidx: number): Promise<boolean>;
  /** compatible.  */
  MIDI_DeleteTextSysexEvt(take: MediaItem_TakeHandle, textsyxevtidx: number): Promise<boolean>;
  /** compatible.  */
  MIDI_DisableSort(take: MediaItem_TakeHandle): Promise<void>;
  /** compatible.  */
  MIDI_EnumSelCC(take: MediaItem_TakeHandle, ccidx: number): Promise<number>;
  /** compatible.  */
  MIDI_EnumSelEvts(take: MediaItem_TakeHandle, evtidx: number): Promise<number>;
  /** compatible.  */
  MIDI_EnumSelNotes(take: MediaItem_TakeHandle, noteidx: number): Promise<number>;
  /** compatible.  */
  MIDI_EnumSelTextSysexEvts(take: MediaItem_TakeHandle, textsyxidx: number): Promise<number>;
  /** compatible.  */
  MIDI_GetAllEvts(take: MediaItem_TakeHandle): Promise<[boolean, Uint8Array]>;
  /** compatible.  */
  MIDI_GetCC(take: MediaItem_TakeHandle, ccidx: number): Promise<[boolean, boolean, boolean, number, number, number, number, number]>;
  /** compatible.  */
  MIDI_GetCCShape(take: MediaItem_TakeHandle, ccidx: number): Promise<[boolean, number, number]>;
  /** compatible.  */
  MIDI_GetEvt(take: MediaItem_TakeHandle, evtidx: number): Promise<[boolean, boolean, boolean, number, Uint8Array]>;
  /** compatible.  */
  MIDI_GetGrid(take: MediaItem_TakeHandle): Promise<[number, number, number]>;
  /** compatible.  */
  MIDI_GetHash(take: MediaItem_TakeHandle, notesonly: boolean): Promise<[boolean, string]>;
  /** compatible.  */
  MIDI_GetNote(take: MediaItem_TakeHandle, noteidx: number): Promise<[boolean, boolean, boolean, number, number, number, number, number]>;
  /** compatible.  */
  MIDI_GetPPQPosFromProjQN(take: MediaItem_TakeHandle, projqn: number): Promise<number>;
  /** compatible.  */
  MIDI_GetPPQPosFromProjTime(take: MediaItem_TakeHandle, projtime: number): Promise<number>;
  /** compatible.  */
  MIDI_GetPPQPos_EndOfMeasure(take: MediaItem_TakeHandle, ppqpos: number): Promise<number>;
  /** compatible.  */
  MIDI_GetPPQPos_StartOfMeasure(take: MediaItem_TakeHandle, ppqpos: number): Promise<number>;
  /** compatible.  */
  MIDI_GetProjQNFromPPQPos(take: MediaItem_TakeHandle, ppqpos: number): Promise<number>;
  /** compatible.  */
  MIDI_GetProjTimeFromPPQPos(take: MediaItem_TakeHandle, ppqpos: number): Promise<number>;
  /** compatible.  */
  MIDI_GetRecentInputEvent(idx: number): Promise<[number, Uint8Array, number, number, number, number]>;
  /** compatible.  */
  MIDI_GetScale(take: MediaItem_TakeHandle): Promise<[boolean, number, number, string]>;
  /** compatible.  */
  MIDI_GetTextSysexEvt(take: MediaItem_TakeHandle, textsyxevtidx: number, selected?: boolean, muted?: boolean, ppqpos?: number, type?: number, msg?: Uint8Array | string): Promise<[boolean, boolean, boolean, number, number, Uint8Array]>;
  /** compatible.  */
  MIDI_GetTrackHash(track: MediaTrackHandle, notesonly: boolean): Promise<[boolean, string]>;
  /** compatible.  */
  MIDI_InsertCC(take: MediaItem_TakeHandle, selected: boolean, muted: boolean, ppqpos: number, chanmsg: number, chan: number, msg2: number, msg3: number): Promise<boolean>;
  /** compatible.  */
  MIDI_InsertEvt(take: MediaItem_TakeHandle, selected: boolean, muted: boolean, ppqpos: number, bytestr: Uint8Array | string): Promise<boolean>;
  /** compatible.  */
  MIDI_InsertNote(take: MediaItem_TakeHandle, selected: boolean, muted: boolean, startppqpos: number, endppqpos: number, chan: number, pitch: number, vel: number, noSortIn?: boolean): Promise<boolean>;
  /** compatible.  */
  MIDI_InsertTextSysexEvt(take: MediaItem_TakeHandle, selected: boolean, muted: boolean, ppqpos: number, type: number, bytestr: Uint8Array | string): Promise<boolean>;
  /** compatible.  */
  MIDI_RefreshEditors(tk: MediaItem_TakeHandle): Promise<void>;
  /** compatible.  */
  MIDI_SelectAll(take: MediaItem_TakeHandle, select: boolean): Promise<void>;
  /** compatible.  */
  MIDI_SetAllEvts(take: MediaItem_TakeHandle, buf: Uint8Array | string): Promise<boolean>;
  /** compatible.  */
  MIDI_SetCC(take: MediaItem_TakeHandle, ccidx: number, selectedIn?: boolean, mutedIn?: boolean, ppqposIn?: number, chanmsgIn?: number, chanIn?: number, msg2In?: number, msg3In?: number, noSortIn?: boolean): Promise<boolean>;
  /** compatible.  */
  MIDI_SetCCShape(take: MediaItem_TakeHandle, ccidx: number, shape: number, beztension: number, noSortIn?: boolean): Promise<boolean>;
  /** compatible.  */
  MIDI_SetEvt(take: MediaItem_TakeHandle, evtidx: number, selectedIn?: boolean, mutedIn?: boolean, ppqposIn?: number, msg?: Uint8Array | string, noSortIn?: boolean): Promise<boolean>;
  /** compatible.  */
  MIDI_SetItemExtents(item: MediaItemHandle, startQN: number, endQN: number): Promise<boolean>;
  /** compatible.  */
  MIDI_SetNote(take: MediaItem_TakeHandle, noteidx: number, selectedIn?: boolean, mutedIn?: boolean, startppqposIn?: number, endppqposIn?: number, chanIn?: number, pitchIn?: number, velIn?: number, noSortIn?: boolean): Promise<boolean>;
  /** compatible.  */
  MIDI_SetTextSysexEvt(take: MediaItem_TakeHandle, textsyxevtidx: number, selectedIn?: boolean, mutedIn?: boolean, ppqposIn?: number, typeIn?: number, msg?: Uint8Array | string, noSortIn?: boolean): Promise<boolean>;
  /** compatible.  */
  MIDI_Sort(take: MediaItem_TakeHandle): Promise<void>;
  /** compatible.  */
  Main_OnCommand(command: number, flag: number): Promise<void>;
  /** compatible.  */
  Main_OnCommandEx(command: number, flag: number, proj: ReaProjectHandle | null | 0): Promise<void>;
  /** compatible.  */
  Main_SaveProject(proj: ReaProjectHandle | null | 0, forceSaveAsIn: boolean): Promise<void>;
  /** compatible.  */
  Main_SaveProjectEx(proj: ReaProjectHandle | null | 0, filename: string, options: number): Promise<void>;
  /** compatible.  */
  Main_UpdateLoopInfo(ignoremask: number): Promise<void>;
  /** compatible.  */
  Main_openProject(name: string): Promise<void>;
  /** compatible.  */
  MarkProjectDirty(proj: ReaProjectHandle | null | 0): Promise<void>;
  /** compatible.  */
  MarkTrackItemsDirty(track: MediaTrackHandle, item: MediaItemHandle): Promise<void>;
  /** compatible.  */
  Master_GetPlayRate(project: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  Master_GetPlayRateAtTime(time_s: number, proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  Master_GetTempo(): Promise<number>;
  /** compatible.  */
  Master_NormalizePlayRate(playrate: number, isnormalized: boolean): Promise<number>;
  /** compatible.  */
  Master_NormalizeTempo(bpm: number, isnormalized: boolean): Promise<number>;
  /** compatible.  */
  MediaExplorerGetLastPlayedFileInfo(): Promise<[boolean, string, number, number, number, number, number, number, number, string]>;
  /** compatible.  */
  MediaItemDescendsFromTrack(item: MediaItemHandle, track: MediaTrackHandle): Promise<number>;
  /** compatible.  */
  Menu_GetHash(menuname: string, flag: number): Promise<[boolean, string]>;
  /** compatible.  */
  MoveEditCursor(adjamt: number, dosel: boolean): Promise<void>;
  /** compatible.  */
  MoveMediaItemToTrack(item: MediaItemHandle, desttr: MediaTrackHandle): Promise<boolean>;
  /** compatible.  */
  MuteAllTracks(mute: boolean): Promise<void>;
  /** compatible.  */
  NamedCommandLookup(command_name: string): Promise<number>;
  /** compatible.  */
  OnPauseButton(): Promise<void>;
  /** compatible.  */
  OnPauseButtonEx(proj: ReaProjectHandle | null | 0): Promise<void>;
  /** compatible.  */
  OnPlayButton(): Promise<void>;
  /** compatible.  */
  OnPlayButtonEx(proj: ReaProjectHandle | null | 0): Promise<void>;
  /** compatible.  */
  OnStopButton(): Promise<void>;
  /** compatible.  */
  OnStopButtonEx(proj: ReaProjectHandle | null | 0): Promise<void>;
  /** compatible.  */
  OpenColorThemeFile(fn: string): Promise<boolean>;
  /** compatible.  */
  OpenMediaExplorer(mediafn: string, play: boolean): Promise<HWNDHandle | null>;
  /** compatible.  */
  OscLocalMessageToHost(message: string, valueIn?: number): Promise<void>;
  /** compatible.  */
  PCM_Sink_Enum(idx: number): Promise<[number, string | null]>;
  /** compatible.  */
  PCM_Sink_GetExtension(data: Uint8Array | string): Promise<string | null>;
  /** compatible.  */
  PCM_Sink_ShowConfig(cfg: Uint8Array | string, hwndParent: HWNDHandle | null): Promise<HWNDHandle | null>;
  /** compatible.  */
  PCM_Source_BuildPeaks(src: PCM_sourceHandle, mode: number): Promise<number>;
  /** compatible.  */
  PCM_Source_CreateFromFile(filename: string): Promise<PCM_sourceHandle | null>;
  /** compatible.  */
  PCM_Source_CreateFromFileEx(filename: string, forcenoMidiImp: boolean): Promise<PCM_sourceHandle | null>;
  /** compatible.  */
  PCM_Source_CreateFromType(sourcetype: string): Promise<PCM_sourceHandle | null>;
  /** compatible.  */
  PCM_Source_Destroy(src: PCM_sourceHandle): Promise<void>;
  /** compatible.  */
  PCM_Source_GetPeaks(src: PCM_sourceHandle, peakrate: number, starttime: number, numchannels: number, numsamplesperchannel: number, want_extra_type: number, buf: Float64Array | number[]): Promise<number>;
  /** compatible.  */
  PCM_Source_GetSectionInfo(src: PCM_sourceHandle): Promise<[boolean, number, number, boolean]>;
  /** compatible.  */
  PluginWantsAlwaysRunFx(amt: number): Promise<void>;
  /** compatible.  */
  PreventUIRefresh(prevent_count: number): Promise<void>;
  /** compatible.  */
  PromptForAction(session_mode: number, init_id: number, section_id: number): Promise<number>;
  /** compatible.  */
  ReaScriptError(errmsg: string): Promise<void>;
  /** compatible.  */
  RecursiveCreateDirectory(path: string, ignored: number): Promise<number>;
  /** compatible.  */
  RefreshToolbar(command_id: number): Promise<void>;
  /** compatible.  */
  RefreshToolbar2(section_id: number, command_id: number): Promise<void>;
  /** compatible.  */
  RemoveTrackSend(tr: MediaTrackHandle, category: number, sendidx: number): Promise<boolean>;
  /** compatible.  */
  RenderFileSection(source_filename: string, target_filename: string, start_percent: number, end_percent: number, playrate: number): Promise<boolean>;
  /** compatible.  */
  ReorderSelectedTracks(beforeTrackIdx: number, makePrevFolder: number): Promise<boolean>;
  /** compatible.  */
  Resample_EnumModes(mode: number): Promise<string | null>;
  /** compatible.  */
  ResolveWildcards(project: ReaProjectHandle | null | 0, timePosition: number, wildcards: string, resolvedString: string): Promise<string>;
  /** compatible.  */
  ReverseNamedCommandLookup(command_id: number): Promise<string | null>;
  /** compatible.  */
  SLIDER2DB(y: number): Promise<number>;
  /** compatible.  */
  ScaleFromEnvelopeMode(scaling_mode: number, val: number): Promise<number>;
  /** compatible.  */
  ScaleToEnvelopeMode(scaling_mode: number, val: number): Promise<number>;
  /** compatible.  */
  SectionFromUniqueID(uniqueID: number): Promise<KbdSectionInfoHandle | null>;
  /** compatible.  */
  SelectAllMediaItems(proj: ReaProjectHandle | null | 0, selected: boolean): Promise<void>;
  /** compatible.  */
  SelectProjectInstance(proj: ReaProjectHandle | null | 0): Promise<void>;
  /** compatible.  */
  SendMIDIMessageToHardware(output: number, msg: Uint8Array | string): Promise<void>;
  /** compatible.  */
  SetActiveTake(take: MediaItem_TakeHandle): Promise<void>;
  /** compatible.  */
  SetAutomationMode(mode: number, onlySel: boolean): Promise<void>;
  /** compatible.  */
  SetCurrentBPM(__proj: ReaProjectHandle | null | 0, bpm: number, wantUndo: boolean): Promise<void>;
  /** compatible.  */
  SetCursorContext(mode: number, envIn: TrackEnvelopeHandle | null): Promise<void>;
  /** compatible.  */
  SetEditCurPos(time: number, moveview: boolean, seekplay: boolean): Promise<void>;
  /** compatible.  */
  SetEditCurPos2(proj: ReaProjectHandle | null | 0, time: number, moveview: boolean, seekplay: boolean): Promise<void>;
  /** compatible.  */
  SetEnvelopePoint(envelope: TrackEnvelopeHandle, ptidx: number, timeIn?: number, valueIn?: number, shapeIn?: number, tensionIn?: number, selectedIn?: boolean, noSortIn?: boolean): Promise<boolean>;
  /** compatible.  */
  SetEnvelopePointEx(envelope: TrackEnvelopeHandle, autoitem_idx: number, ptidx: number, timeIn?: number, valueIn?: number, shapeIn?: number, tensionIn?: number, selectedIn?: boolean, noSortIn?: boolean): Promise<boolean>;
  /** compatible.  */
  SetEnvelopeStateChunk(env: TrackEnvelopeHandle, str: string, isundo: boolean): Promise<boolean>;
  /** compatible.  */
  SetExtState(section: string, key: string, value: string, persist: boolean): Promise<void>;
  /** compatible.  */
  SetGlobalAutomationOverride(mode: number): Promise<void>;
  /** compatible.  */
  SetItemStateChunk(item: MediaItemHandle, str: string, isundo: boolean): Promise<boolean>;
  /** compatible.  */
  SetMIDIEditorGrid(project: ReaProjectHandle | null | 0, division: number): Promise<void>;
  /** compatible.  */
  SetMasterTrackVisibility(flag: number): Promise<number>;
  /** compatible.  */
  SetMediaItemInfo_Value(item: MediaItemHandle, parmname: string, newvalue: number): Promise<boolean>;
  /** compatible.  */
  SetMediaItemLength(item: MediaItemHandle, length: number, refreshUI: boolean): Promise<boolean>;
  /** compatible.  */
  SetMediaItemPosition(item: MediaItemHandle, position: number, refreshUI: boolean): Promise<boolean>;
  /** compatible.  */
  SetMediaItemSelected(item: MediaItemHandle, selected: boolean): Promise<void>;
  /** compatible.  */
  SetMediaItemTakeInfo_Value(take: MediaItem_TakeHandle, parmname: string, newvalue: number): Promise<boolean>;
  /** compatible.  */
  SetMediaItemTake_Source(take: MediaItem_TakeHandle, source: PCM_sourceHandle): Promise<boolean>;
  /** compatible.  */
  SetMediaTrackInfo_Value(tr: MediaTrackHandle, parmname: string, newvalue: number): Promise<boolean>;
  /** compatible.  */
  SetMixerScroll(leftmosttrack: MediaTrackHandle): Promise<MediaTrackHandle | null>;
  /** compatible.  */
  SetMouseModifier(context: string, modifier_flag: number, action: string): Promise<void>;
  /** compatible.  */
  SetOnlyTrackSelected(track: MediaTrackHandle | null): Promise<void>;
  /** compatible.  */
  SetProjExtState(proj: ReaProjectHandle | null | 0, extname: string, key: string, value: string): Promise<number>;
  /** compatible.  */
  SetProjectGrid(project: ReaProjectHandle | null | 0, division: number): Promise<void>;
  /** compatible.  */
  SetProjectMarker(markrgnindexnumber: number, isrgn: boolean, pos: number, rgnend: number, name: string): Promise<boolean>;
  /** compatible.  */
  SetProjectMarker2(proj: ReaProjectHandle | null | 0, markrgnindexnumber: number, isrgn: boolean, pos: number, rgnend: number, name: string): Promise<boolean>;
  /** compatible.  */
  SetProjectMarker3(proj: ReaProjectHandle | null | 0, markrgnindexnumber: number, isrgn: boolean, pos: number, rgnend: number, name: string, color: number): Promise<boolean>;
  /** compatible.  */
  SetProjectMarker4(proj: ReaProjectHandle | null | 0, markrgnindexnumber: number, isrgn: boolean, pos: number, rgnend: number, name: string, color: number, flags: number): Promise<boolean>;
  /** compatible.  */
  SetProjectMarkerByIndex(proj: ReaProjectHandle | null | 0, markrgnidx: number, isrgn: boolean, pos: number, rgnend: number, IDnumber: number, name: string, color: number): Promise<boolean>;
  /** compatible.  */
  SetProjectMarkerByIndex2(proj: ReaProjectHandle | null | 0, markrgnidx: number, isrgn: boolean, pos: number, rgnend: number, IDnumber: number, name: string, color: number, flags: number): Promise<boolean>;
  /** compatible.  */
  SetRegionOrMarkerInfo_Value(proj: ReaProjectHandle | null | 0, regionOrMarker: ProjectMarkerHandle, parameterName: string, setNewValue: number): Promise<number>;
  /** compatible.  */
  SetRegionRenderMatrix(proj: ReaProjectHandle | null | 0, regionindex: number, track: MediaTrackHandle, flag: number): Promise<void>;
  /** compatible.  */
  SetTakeMarker(take: MediaItem_TakeHandle, idx: number, nameIn: string, srcposIn?: number, colorIn?: number): Promise<number>;
  /** compatible.  */
  SetTakeStretchMarker(take: MediaItem_TakeHandle, idx: number, pos: number, srcposIn?: number): Promise<number>;
  /** compatible.  */
  SetTakeStretchMarkerSlope(take: MediaItem_TakeHandle, idx: number, slope: number): Promise<boolean>;
  /** compatible.  */
  SetTempoTimeSigMarker(proj: ReaProjectHandle | null | 0, ptidx: number, timepos: number, measurepos: number, beatpos: number, bpm: number, timesig_num: number, timesig_denom: number, lineartempo: boolean): Promise<boolean>;
  /** compatible.  */
  SetThemeColor(ini_key: string, color: number, flags: number): Promise<number>;
  /** compatible.  */
  SetToggleCommandState(section_id: number, command_id: number, state: number): Promise<boolean>;
  /** compatible.  */
  SetTrackAutomationMode(tr: MediaTrackHandle, mode: number): Promise<void>;
  /** compatible.  */
  SetTrackColor(track: MediaTrackHandle, color: number): Promise<void>;
  /** compatible.  */
  SetTrackMIDILyrics(track: MediaTrackHandle, flag: number, str: string): Promise<boolean>;
  /** compatible.  */
  SetTrackMIDINoteName(track: number, pitch: number, chan: number, name: string): Promise<boolean>;
  /** compatible.  */
  SetTrackMIDINoteNameEx(proj: ReaProjectHandle | null | 0, track: MediaTrackHandle, pitch: number, chan: number, name: string): Promise<boolean>;
  /** compatible.  */
  SetTrackSelected(track: MediaTrackHandle, selected: boolean): Promise<void>;
  /** compatible.  */
  SetTrackSendInfo_Value(tr: MediaTrackHandle, category: number, sendidx: number, parmname: string, newvalue: number): Promise<boolean>;
  /** compatible.  */
  SetTrackSendUIPan(track: MediaTrackHandle, send_idx: number, pan: number, isend: number): Promise<boolean>;
  /** compatible.  */
  SetTrackSendUIVol(track: MediaTrackHandle, send_idx: number, vol: number, isend: number): Promise<boolean>;
  /** compatible.  */
  SetTrackStateChunk(track: MediaTrackHandle, str: string, isundo: boolean): Promise<boolean>;
  /** compatible.  */
  SetTrackUIInputMonitor(track: MediaTrackHandle, monitor: number, igngroupflags: number): Promise<number>;
  /** compatible.  */
  SetTrackUIMute(track: MediaTrackHandle, mute: number, igngroupflags: number): Promise<number>;
  /** compatible.  */
  SetTrackUIPan(track: MediaTrackHandle, pan: number, relative: boolean, done: boolean, igngroupflags: number): Promise<number>;
  /** compatible.  */
  SetTrackUIPolarity(track: MediaTrackHandle, polarity: number, igngroupflags: number): Promise<number>;
  /** compatible.  */
  SetTrackUIRecArm(track: MediaTrackHandle, recarm: number, igngroupflags: number): Promise<number>;
  /** compatible.  */
  SetTrackUISolo(track: MediaTrackHandle, solo: number, igngroupflags: number): Promise<number>;
  /** compatible.  */
  SetTrackUIVolume(track: MediaTrackHandle, volume: number, relative: boolean, done: boolean, igngroupflags: number): Promise<number>;
  /** compatible.  */
  SetTrackUIWidth(track: MediaTrackHandle, width: number, relative: boolean, done: boolean, igngroupflags: number): Promise<number>;
  /** compatible.  */
  ShowActionList(section: KbdSectionInfoHandle | null | 0, callerWnd: HWNDHandle | null): Promise<void>;
  /** compatible.  */
  ShowConsoleMsg(msg: string): Promise<void>;
  /** compatible.  */
  ShowMessageBox(msg: string, title: string, type: number): Promise<number>;
  /** compatible.  */
  ShowPopupMenu(name: string, x: number, y: number, hwndParent: HWNDHandle | null, ctx: ReaWebHandle | null, ctx2: number, ctx3: number): Promise<void>;
  /** compatible.  */
  SnapToGrid(project: ReaProjectHandle | null | 0, time_pos: number): Promise<number>;
  /** compatible.  */
  SoloAllTracks(solo: number): Promise<void>;
  /** compatible.  */
  Splash_GetWnd(): Promise<HWNDHandle | null>;
  /** compatible.  */
  SplitMediaItem(item: MediaItemHandle, position: number): Promise<MediaItemHandle | null>;
  /** compatible.  */
  StuffMIDIMessage(mode: number, msg1: number, msg2: number, msg3: number): Promise<void>;
  /** compatible.  */
  TakeFX_AddByName(take: MediaItem_TakeHandle, fxname: string, instantiate: number): Promise<number>;
  /** compatible.  */
  TakeFX_CopyToTake(src_take: MediaItem_TakeHandle, src_fx: number, dest_take: MediaItem_TakeHandle, dest_fx: number, is_move: boolean): Promise<void>;
  /** compatible.  */
  TakeFX_CopyToTrack(src_take: MediaItem_TakeHandle, src_fx: number, dest_track: MediaTrackHandle, dest_fx: number, is_move: boolean): Promise<void>;
  /** compatible.  */
  TakeFX_Delete(take: MediaItem_TakeHandle, fx: number): Promise<boolean>;
  /** compatible.  */
  TakeFX_EndParamEdit(take: MediaItem_TakeHandle, fx: number, param: number): Promise<boolean>;
  /** compatible.  */
  TakeFX_FormatParamValue(take: MediaItem_TakeHandle, fx: number, param: number, val: number): Promise<[boolean, string]>;
  /** compatible.  */
  TakeFX_FormatParamValueNormalized(take: MediaItem_TakeHandle, fx: number, param: number, value: number): Promise<[boolean, string]>;
  /** compatible.  */
  TakeFX_GetChainVisible(take: MediaItem_TakeHandle): Promise<number>;
  /** compatible.  */
  TakeFX_GetCount(take: MediaItem_TakeHandle): Promise<number>;
  /** compatible.  */
  TakeFX_GetEnabled(take: MediaItem_TakeHandle, fx: number): Promise<boolean>;
  /** compatible.  */
  TakeFX_GetEnvelope(take: MediaItem_TakeHandle, fxindex: number, parameterindex: number, create: boolean): Promise<TrackEnvelopeHandle | null>;
  /** compatible.  */
  TakeFX_GetFXGUID(take: MediaItem_TakeHandle, fx: number): Promise<string | null>;
  /** compatible.  */
  TakeFX_GetFXName(take: MediaItem_TakeHandle, fx: number): Promise<[boolean, string]>;
  /** compatible.  */
  TakeFX_GetFloatingWindow(take: MediaItem_TakeHandle, index: number): Promise<HWNDHandle | null>;
  /** compatible.  */
  TakeFX_GetFormattedParamValue(take: MediaItem_TakeHandle, fx: number, param: number): Promise<[boolean, string]>;
  /** compatible.  */
  TakeFX_GetIOSize(take: MediaItem_TakeHandle, fx: number): Promise<[number, number, number]>;
  /** compatible.  */
  TakeFX_GetNamedConfigParm(take: MediaItem_TakeHandle, fx: number, parmname: string): Promise<[boolean, string]>;
  /** compatible.  */
  TakeFX_GetNumParams(take: MediaItem_TakeHandle, fx: number): Promise<number>;
  /** compatible.  */
  TakeFX_GetOffline(take: MediaItem_TakeHandle, fx: number): Promise<boolean>;
  /** compatible.  */
  TakeFX_GetOpen(take: MediaItem_TakeHandle, fx: number): Promise<boolean>;
  /** compatible.  */
  TakeFX_GetParam(take: MediaItem_TakeHandle, fx: number, param: number): Promise<[number, number, number]>;
  /** compatible.  */
  TakeFX_GetParamEx(take: MediaItem_TakeHandle, fx: number, param: number): Promise<[number, number, number, number]>;
  /** compatible.  */
  TakeFX_GetParamFromIdent(take: MediaItem_TakeHandle, fx: number, ident_str: string): Promise<number>;
  /** compatible.  */
  TakeFX_GetParamIdent(take: MediaItem_TakeHandle, fx: number, param: number): Promise<[boolean, string]>;
  /** compatible.  */
  TakeFX_GetParamName(take: MediaItem_TakeHandle, fx: number, param: number): Promise<[boolean, string]>;
  /** compatible.  */
  TakeFX_GetParamNormalized(take: MediaItem_TakeHandle, fx: number, param: number): Promise<number>;
  /** compatible.  */
  TakeFX_GetParamSectionName(take: MediaItem_TakeHandle, fx: number, param: number): Promise<string>;
  /** compatible.  */
  TakeFX_GetParameterStepSizes(take: MediaItem_TakeHandle, fx: number, param: number): Promise<[boolean, number, number, number, boolean]>;
  /** compatible.  */
  TakeFX_GetPinMappings(take: MediaItem_TakeHandle, fx: number, isoutput: number, pin: number): Promise<[number, number]>;
  /** compatible.  */
  TakeFX_GetPreset(take: MediaItem_TakeHandle, fx: number): Promise<[boolean, string]>;
  /** compatible.  */
  TakeFX_GetPresetIndex(take: MediaItem_TakeHandle, fx: number): Promise<[number, number]>;
  /** compatible.  */
  TakeFX_GetUserPresetFilename(take: MediaItem_TakeHandle, fx: number): Promise<string>;
  /** compatible.  */
  TakeFX_NavigatePresets(take: MediaItem_TakeHandle, fx: number, presetmove: number): Promise<boolean>;
  /** compatible.  */
  TakeFX_SetEnabled(take: MediaItem_TakeHandle, fx: number, enabled: boolean): Promise<void>;
  /** compatible.  */
  TakeFX_SetNamedConfigParm(take: MediaItem_TakeHandle, fx: number, parmname: string, value: string): Promise<boolean>;
  /** compatible.  */
  TakeFX_SetOffline(take: MediaItem_TakeHandle, fx: number, offline: boolean): Promise<void>;
  /** compatible.  */
  TakeFX_SetOpen(take: MediaItem_TakeHandle, fx: number, open: boolean): Promise<void>;
  /** compatible.  */
  TakeFX_SetParam(take: MediaItem_TakeHandle, fx: number, param: number, val: number): Promise<boolean>;
  /** compatible.  */
  TakeFX_SetParamNormalized(take: MediaItem_TakeHandle, fx: number, param: number, value: number): Promise<boolean>;
  /** compatible.  */
  TakeFX_SetPinMappings(take: MediaItem_TakeHandle, fx: number, isoutput: number, pin: number, low32bits: number, hi32bits: number): Promise<boolean>;
  /** compatible.  */
  TakeFX_SetPreset(take: MediaItem_TakeHandle, fx: number, presetname: string): Promise<boolean>;
  /** compatible.  */
  TakeFX_SetPresetByIndex(take: MediaItem_TakeHandle, fx: number, idx: number): Promise<boolean>;
  /** compatible.  */
  TakeFX_Show(take: MediaItem_TakeHandle, index: number, showFlag: number): Promise<void>;
  /** compatible.  */
  TakeIsMIDI(take: MediaItem_TakeHandle): Promise<boolean>;
  /** compatible.  */
  ThemeLayout_GetLayout(section: string, idx: number): Promise<[boolean, string]>;
  /** compatible.  */
  ThemeLayout_GetParameter(wp: number): Promise<[string | null, string | null, number, number, number, number]>;
  /** compatible.  */
  ThemeLayout_RefreshAll(): Promise<void>;
  /** compatible.  */
  ThemeLayout_SetLayout(section: string, layout: string): Promise<boolean>;
  /** compatible.  */
  ThemeLayout_SetParameter(wp: number, value: number, persist: boolean): Promise<boolean>;
  /** compatible.  */
  TimeMap2_GetDividedBpmAtTime(proj: ReaProjectHandle | null | 0, time: number): Promise<number>;
  /** compatible.  */
  TimeMap2_GetNextChangeTime(proj: ReaProjectHandle | null | 0, time: number): Promise<number>;
  /** compatible.  */
  TimeMap2_QNToTime(proj: ReaProjectHandle | null | 0, qn: number): Promise<number>;
  /** compatible.  */
  TimeMap2_beatsToTime(proj: ReaProjectHandle | null | 0, tpos: number, measuresIn?: number): Promise<number>;
  /** compatible.  */
  TimeMap2_timeToBeats(proj: ReaProjectHandle | null | 0, tpos: number): Promise<[number, number, number, number, number]>;
  /** compatible.  */
  TimeMap2_timeToQN(proj: ReaProjectHandle | null | 0, tpos: number): Promise<number>;
  /** compatible.  */
  TimeMap_GetDividedBpmAtTime(time: number): Promise<number>;
  /** compatible.  */
  TimeMap_GetMeasureInfo(proj: ReaProjectHandle | null | 0, measure: number): Promise<[number, number, number, number, number, number]>;
  /** compatible.  */
  TimeMap_GetMetronomePattern(proj: ReaProjectHandle | null | 0, time: number, pattern: string): Promise<[number, string]>;
  /** compatible.  */
  TimeMap_GetTimeSigAtTime(proj: ReaProjectHandle | null | 0, time: number): Promise<[number, number, number]>;
  /** compatible.  */
  TimeMap_QNToMeasures(proj: ReaProjectHandle | null | 0, qn: number): Promise<[number, number, number]>;
  /** compatible.  */
  TimeMap_QNToTime(qn: number): Promise<number>;
  /** compatible.  */
  TimeMap_QNToTime_abs(proj: ReaProjectHandle | null | 0, qn: number): Promise<number>;
  /** compatible.  */
  TimeMap_curFrameRate(proj: ReaProjectHandle | null | 0): Promise<[number, boolean]>;
  /** compatible.  */
  TimeMap_timeToQN(tpos: number): Promise<number>;
  /** compatible.  */
  TimeMap_timeToQN_abs(proj: ReaProjectHandle | null | 0, tpos: number): Promise<number>;
  /** compatible.  */
  ToggleTrackSendUIMute(track: MediaTrackHandle, send_idx: number): Promise<boolean>;
  /** compatible.  */
  TrackCtl_SetToolTip(fmt: string, xpos: number, ypos: number, topmost: boolean): Promise<void>;
  /** compatible.  */
  TrackFX_AddByName(track: MediaTrackHandle, fxname: string, recFX: boolean, instantiate: number): Promise<number>;
  /** compatible.  */
  TrackFX_CopyToTake(src_track: MediaTrackHandle, src_fx: number, dest_take: MediaItem_TakeHandle, dest_fx: number, is_move: boolean): Promise<void>;
  /** compatible.  */
  TrackFX_CopyToTrack(src_track: MediaTrackHandle, src_fx: number, dest_track: MediaTrackHandle, dest_fx: number, is_move: boolean): Promise<void>;
  /** compatible.  */
  TrackFX_Delete(track: MediaTrackHandle, fx: number): Promise<boolean>;
  /** compatible.  */
  TrackFX_EndParamEdit(track: MediaTrackHandle, fx: number, param: number): Promise<boolean>;
  /** compatible.  */
  TrackFX_FormatParamValue(track: MediaTrackHandle, fx: number, param: number, val: number): Promise<[boolean, string]>;
  /** compatible.  */
  TrackFX_FormatParamValueNormalized(track: MediaTrackHandle, fx: number, param: number, value: number): Promise<[boolean, string]>;
  /** compatible.  */
  TrackFX_GetByName(track: MediaTrackHandle, fxname: string, instantiate: boolean): Promise<number>;
  /** compatible.  */
  TrackFX_GetChainVisible(track: MediaTrackHandle): Promise<number>;
  /** compatible.  */
  TrackFX_GetCount(track: MediaTrackHandle): Promise<number>;
  /** compatible.  */
  TrackFX_GetEQ(track: MediaTrackHandle, instantiate: boolean): Promise<number>;
  /** compatible.  */
  TrackFX_GetEQBandEnabled(track: MediaTrackHandle, fxidx: number, bandtype: number, bandidx: number): Promise<boolean>;
  /** compatible.  */
  TrackFX_GetEQParam(track: MediaTrackHandle, fxidx: number, paramidx: number): Promise<[boolean, number, number, number, number]>;
  /** compatible.  */
  TrackFX_GetEnabled(track: MediaTrackHandle, fx: number): Promise<boolean>;
  /** compatible.  */
  TrackFX_GetFXGUID(track: MediaTrackHandle, fx: number): Promise<string | null>;
  /** compatible.  */
  TrackFX_GetFXName(track: MediaTrackHandle, fx: number): Promise<[boolean, string]>;
  /** compatible.  */
  TrackFX_GetFloatingWindow(track: MediaTrackHandle, index: number): Promise<HWNDHandle | null>;
  /** compatible.  */
  TrackFX_GetFormattedParamValue(track: MediaTrackHandle, fx: number, param: number): Promise<[boolean, string]>;
  /** compatible.  */
  TrackFX_GetIOSize(track: MediaTrackHandle, fx: number): Promise<[number, number, number]>;
  /** compatible.  */
  TrackFX_GetInstrument(track: MediaTrackHandle): Promise<number>;
  /** compatible.  */
  TrackFX_GetNamedConfigParm(track: MediaTrackHandle, fx: number, parmname: string): Promise<[boolean, string]>;
  /** compatible.  */
  TrackFX_GetNumParams(track: MediaTrackHandle, fx: number): Promise<number>;
  /** compatible.  */
  TrackFX_GetOffline(track: MediaTrackHandle, fx: number): Promise<boolean>;
  /** compatible.  */
  TrackFX_GetOpen(track: MediaTrackHandle, fx: number): Promise<boolean>;
  /** compatible.  */
  TrackFX_GetParam(track: MediaTrackHandle, fx: number, param: number): Promise<[number, number, number]>;
  /** compatible.  */
  TrackFX_GetParamEx(track: MediaTrackHandle, fx: number, param: number): Promise<[number, number, number, number]>;
  /** compatible.  */
  TrackFX_GetParamFromIdent(track: MediaTrackHandle, fx: number, ident_str: string): Promise<number>;
  /** compatible.  */
  TrackFX_GetParamIdent(track: MediaTrackHandle, fx: number, param: number): Promise<[boolean, string]>;
  /** compatible.  */
  TrackFX_GetParamName(track: MediaTrackHandle, fx: number, param: number): Promise<[boolean, string]>;
  /** compatible.  */
  TrackFX_GetParamNormalized(track: MediaTrackHandle, fx: number, param: number): Promise<number>;
  /** compatible.  */
  TrackFX_GetParamSectionName(track: MediaTrackHandle, fx: number, param: number): Promise<string>;
  /** compatible.  */
  TrackFX_GetParameterStepSizes(track: MediaTrackHandle, fx: number, param: number): Promise<[boolean, number, number, number, boolean]>;
  /** compatible.  */
  TrackFX_GetPinMappings(tr: MediaTrackHandle, fx: number, isoutput: number, pin: number): Promise<[number, number]>;
  /** compatible.  */
  TrackFX_GetPreset(track: MediaTrackHandle, fx: number): Promise<[boolean, string]>;
  /** compatible.  */
  TrackFX_GetPresetIndex(track: MediaTrackHandle, fx: number): Promise<[number, number]>;
  /** compatible.  */
  TrackFX_GetRecChainVisible(track: MediaTrackHandle): Promise<number>;
  /** compatible.  */
  TrackFX_GetRecCount(track: MediaTrackHandle): Promise<number>;
  /** compatible.  */
  TrackFX_GetUserPresetFilename(track: MediaTrackHandle, fx: number): Promise<string>;
  /** compatible.  */
  TrackFX_NavigatePresets(track: MediaTrackHandle, fx: number, presetmove: number): Promise<boolean>;
  /** compatible.  */
  TrackFX_SetEQBandEnabled(track: MediaTrackHandle, fxidx: number, bandtype: number, bandidx: number, enable: boolean): Promise<boolean>;
  /** compatible.  */
  TrackFX_SetEQParam(track: MediaTrackHandle, fxidx: number, bandtype: number, bandidx: number, paramtype: number, val: number, isnorm: boolean): Promise<boolean>;
  /** compatible.  */
  TrackFX_SetEnabled(track: MediaTrackHandle, fx: number, enabled: boolean): Promise<void>;
  /** compatible.  */
  TrackFX_SetNamedConfigParm(track: MediaTrackHandle, fx: number, parmname: string, value: string): Promise<boolean>;
  /** compatible.  */
  TrackFX_SetOffline(track: MediaTrackHandle, fx: number, offline: boolean): Promise<void>;
  /** compatible.  */
  TrackFX_SetOpen(track: MediaTrackHandle, fx: number, open: boolean): Promise<void>;
  /** compatible.  */
  TrackFX_SetParam(track: MediaTrackHandle, fx: number, param: number, val: number): Promise<boolean>;
  /** compatible.  */
  TrackFX_SetParamNormalized(track: MediaTrackHandle, fx: number, param: number, value: number): Promise<boolean>;
  /** compatible.  */
  TrackFX_SetPinMappings(tr: MediaTrackHandle, fx: number, isoutput: number, pin: number, low32bits: number, hi32bits: number): Promise<boolean>;
  /** compatible.  */
  TrackFX_SetPreset(track: MediaTrackHandle, fx: number, presetname: string): Promise<boolean>;
  /** compatible.  */
  TrackFX_SetPresetByIndex(track: MediaTrackHandle, fx: number, idx: number): Promise<boolean>;
  /** compatible.  */
  TrackFX_Show(track: MediaTrackHandle, index: number, showFlag: number): Promise<void>;
  /** compatible.  */
  TrackList_AdjustWindows(isMinor: boolean): Promise<void>;
  /** compatible.  */
  TrackList_UpdateAllExternalSurfaces(): Promise<void>;
  /** compatible.  */
  Track_GetPeakHoldDB(track: MediaTrackHandle, channel: number, clear: boolean): Promise<number>;
  /** compatible.  */
  Track_GetPeakInfo(track: MediaTrackHandle, channel: number): Promise<number>;
  /** compatible.  */
  Undo_BeginBlock(): Promise<void>;
  /** compatible.  */
  Undo_BeginBlock2(proj: ReaProjectHandle | null | 0): Promise<void>;
  /** compatible.  */
  Undo_CanRedo2(proj: ReaProjectHandle | null | 0): Promise<string | null>;
  /** compatible.  */
  Undo_CanUndo2(proj: ReaProjectHandle | null | 0): Promise<string | null>;
  /** compatible.  */
  Undo_DoRedo2(proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  Undo_DoUndo2(proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  Undo_EndBlock(descchange: string, extraflags: number): Promise<void>;
  /** compatible.  */
  Undo_EndBlock2(proj: ReaProjectHandle | null | 0, descchange: string, extraflags: number): Promise<void>;
  /** compatible.  */
  Undo_GetCurEntry(proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  Undo_GetEntryDesc(proj: ReaProjectHandle | null | 0, index: number): Promise<string | null>;
  /** compatible.  */
  Undo_GetEntryTime(proj: ReaProjectHandle | null | 0, index: number): Promise<number>;
  /** compatible.  */
  Undo_GetNumEntries(proj: ReaProjectHandle | null | 0): Promise<number>;
  /** compatible.  */
  Undo_IsEntryAltTree(proj: ReaProjectHandle | null | 0, index: number): Promise<number>;
  /** compatible.  */
  Undo_OnStateChange(descchange: string): Promise<void>;
  /** compatible.  */
  Undo_OnStateChange2(proj: ReaProjectHandle | null | 0, descchange: string): Promise<void>;
  /** compatible.  */
  Undo_OnStateChangeEx(descchange: string, whichStates: number, trackparm: number): Promise<void>;
  /** compatible.  */
  Undo_OnStateChangeEx2(proj: ReaProjectHandle | null | 0, descchange: string, whichStates: number, trackparm: number): Promise<void>;
  /** compatible.  */
  Undo_OnStateChange_Item(proj: ReaProjectHandle | null | 0, name: string, item: MediaItemHandle): Promise<void>;
  /** compatible.  */
  Undo_SetCurPos(proj: ReaProjectHandle | null | 0, index: number, loadAltTree: number): Promise<void>;
  /** compatible.  */
  UpdateArrange(): Promise<void>;
  /** compatible.  */
  UpdateItemInProject(item: MediaItemHandle): Promise<void>;
  /** compatible.  */
  UpdateItemLanes(proj: ReaProjectHandle | null | 0): Promise<boolean>;
  /** compatible.  */
  UpdateTimeline(): Promise<void>;
  /** compatible.  */
  ValidatePtr(pointer: ReaWebHandle | null, ctypename: string): Promise<boolean>;
  /** compatible.  */
  ValidatePtr2(proj: ReaProjectHandle | null | 0, pointer: ReaWebHandle | null, ctypename: string): Promise<boolean>;
  /** compatible.  */
  ViewPrefs(page: number, pageByName: string): Promise<void>;
  /** compatible.  */
  adjustZoom(amt: number, forceset: number, doupd: boolean, centermode: number): Promise<void>;
  /** compatible.  */
  file_exists(path: string): Promise<boolean>;
  /** compatible.  */
  format_timestr(tpos: number, buf: string): Promise<string>;
  /** compatible.  */
  format_timestr_len(tpos: number, buf: string, offset: number, modeoverride: number): Promise<string>;
  /** compatible.  */
  format_timestr_pos(tpos: number, buf: string, modeoverride: number): Promise<string>;
  /** compatible.  */
  genGuid(gGUID: string): Promise<string>;
  /** compatible.  */
  get_config_var_string(name: string): Promise<[boolean, string]>;
  /** compatible.  */
  get_ini_file(): Promise<string | null>;
  /** compatible.  */
  guidToString(gGUID: string, destNeed64: string): Promise<string>;
  /** compatible.  */
  image_resolve_fn(in_: string, out: string): Promise<string>;
  /** compatible.  */
  joystick_create(guidGUID: string): Promise<joystick_deviceHandle | null>;
  /** compatible.  */
  joystick_destroy(device: joystick_deviceHandle): Promise<void>;
  /** compatible.  */
  joystick_enum(index: number): Promise<[string | null, string | null]>;
  /** compatible.  */
  joystick_getaxis(dev: joystick_deviceHandle, axis: number): Promise<number>;
  /** compatible.  */
  joystick_getbuttonmask(dev: joystick_deviceHandle): Promise<number>;
  /** compatible.  */
  joystick_getinfo(dev: joystick_deviceHandle): Promise<[number, number, number]>;
  /** compatible.  */
  joystick_getpov(dev: joystick_deviceHandle, pov: number): Promise<number>;
  /** compatible.  */
  joystick_update(dev: joystick_deviceHandle): Promise<boolean>;
  /** compatible.  */
  kbd_enumerateActions(section: KbdSectionInfoHandle | null | 0, idx: number): Promise<[number, string | null]>;
  /** compatible.  */
  kbd_getTextFromCmd(cmd: number, section: KbdSectionInfoHandle | null | 0): Promise<string | null>;
  /** compatible.  */
  midi_init(force_reinit_input: number, force_reinit_output: number): Promise<void>;
  /** compatible.  */
  midi_reinit(): Promise<void>;
  /** compatible.  */
  mkpanstr(strNeed64: string, pan: number): Promise<string>;
  /** compatible.  */
  mkvolpanstr(strNeed64: string, vol: number, pan: number): Promise<string>;
  /** compatible.  */
  mkvolstr(strNeed64: string, vol: number): Promise<string>;
  /** compatible.  */
  my_getViewport(r_left: number, r_top: number, r_right: number, r_bot: number, sr_left: number, sr_top: number, sr_right: number, sr_bot: number, wantWorkArea: boolean): Promise<void>;
  /** compatible.  */
  parse_timestr(buf: string): Promise<number>;
  /** compatible.  */
  parse_timestr_len(buf: string, offset: number, modeoverride: number): Promise<number>;
  /** compatible.  */
  parse_timestr_pos(buf: string, modeoverride: number): Promise<number>;
  /** compatible.  */
  parsepanstr(str: string): Promise<number>;
  /** compatible.  */
  reduce_open_files(flags: number): Promise<number>;
  /** compatible.  */
  relative_fn(in_: string, out: string): Promise<string>;
  /** compatible.  */
  resolve_fn(in_: string, out: string): Promise<string>;
  /** compatible.  */
  resolve_fn2(in_: string, out: string, checkSubDir?: string): Promise<string>;
  /** compatible.  */
  set_config_var_string(name: string, value: string, persist: number): Promise<number>;
  /** compatible.  */
  stringToGuid(str: string, gGUID: string): Promise<string>;
  /** compatible.  */
  time_precise(): Promise<number>;
}
