"""Generate data and declarations, never native implementations."""
import os
import re
import tempfile
from pathlib import Path
from .model import coverage, encode, validate_schema, validate_bindings, js_type_names


def signature(name, entry):
    params = ', '.join(p['name'] + ('?' if p['optional'] else '') + ': ' + p['type'] +
                       (' | null' if p['optional'] and 'null' not in p['type'].split(' | ') else '') for p in entry['parameters'])
    return f"{name}({params}): Promise<{entry['returns']}>;"


def result_names(fn):
    names = [r['name'] for r in fn['returns']]
    return 'undefined' if not names else names[0] if len(names) == 1 else '[' + ', '.join(names) + ']'


def api_reference(schema, manifest):
    rows = ['<!-- Generated by api_sync update. Do not edit. -->', '# REAPER API reference', '',
            '[Developer guide](development.md) | [中文开发指南](development.zh-CN.md) | [Host API](host-api.md)', '',
            f"Catalogue: REAPER **{schema['source']['reaperVersion']}**, **{len(schema['functions'])}** standard C/Lua APIs.", '',
            'All calls use `await reaper.FunctionName(...)`. Signatures below are members of the `ReaWebAPI` TypeScript interface. '
            'Return labels preserve the official Lua order. Single results are scalars, multiple results are arrays, and void resolves to `undefined`.', '',
            '参数及返回顺序遵循 Lua。`?` 表示可选参数，可省略或传 `null`，中间留空须保留参数位置。'
            '对象使用句柄，MIDI 字节使用 `Uint8Array`，音频数组在调用完成后回写。', '',
            'This is the versioned JavaScript contract, not a copy of the full Cockos manual. '
            'Each entry links to official parameter-key, flag, unit and behavioral documentation. '
            'Those online pages may describe a newer REAPER version. See the [conversion and lifetime rules](development.md#calling-conventions).', '',
            '## Categories', '']
    categories = sorted({f['category'] for f in schema['functions'].values()})
    for category in categories:
        names = sorted(n for n, f in schema['functions'].items() if f['category'] == category)
        rows += [f'### {category} ({len(names)})', '', '| API | API | API |', '| --- | --- | --- |']
        for i in range(0, len(names), 3):
            links = [f'[{n}](#{n.lower()})' for n in names[i:i+3]]
            rows.append('| ' + ' | '.join(links + [''] * (3 - len(links))) + ' |')
        rows.append('')
    rows += ['## Functions', '']
    for name, fn in sorted(schema['functions'].items()):
        entry = manifest['functions'].get(name)
        reviewed = entry and entry['signatureHash'] == fn['signatureHash']
        rows += [f'### {name}', '', f"{fn['category']} · [Official reference]({fn['documentation']})", '']
        if reviewed:
            rows += ['```typescript', signature(name, entry), '```', '',
                     '**Resolved result / 返回值顺序:** `' + result_names(fn) + '`.', '']
            if entry['parameters']:
                rows += ['| Input | JavaScript type | Required |', '| --- | --- | --- |']
                for p in entry['parameters']:
                    typ = p['type'] + (' | null' if p['optional'] and 'null' not in p['type'].split(' | ') else '')
                    rows.append('| `' + p['name'] + '` | `' + typ.replace('|', '\\|') + '` | ' + ('No' if p['optional'] else 'Yes') + ' |')
                rows.append('')
            arrays = [p['name'] for p in entry['parameters'] if 'Float64Array' in p['type']]
            if arrays:
                rows += ['**Mutates / 回写:** ' + ', '.join('`' + n + '`' for n in arrays) + ' after `await`. Preserve its length until completion.', '']
            if entry['limitations']:
                rows += ['**Limitations:** ' + ' '.join(entry['limitations']), '']
        else:
            rows += ['**Binding review required.** The current catalogue signature is not yet an accepted JavaScript contract.', '']
        rows += ['**Lua signature / 原始签名:**', '', '```lua', fn['signatures']['lua'], '```', '']
    return '\n'.join(rows)


def sdk_files(manifest, schema):
    bindings = manifest['functions']
    names = sorted(bindings)
    js = '// Generated by api_sync update. Do not edit.\nconst reawebApiMethods = Object.freeze(' + encode(names).rstrip() + ');\n'
    js += 'const reawebApiVoidMethods = Object.freeze(' + encode([n for n in names if bindings[n]['returns'] == 'void']).rstrip() + ');\n'
    ts = ['// Generated by api_sync update from api/bindings.json. Do not edit.',
          '// Only reviewed native bindings are declared here. See api/reaper_api.json for the catalogue.',
          'interface ReaWebAPI {']
    for name in names:
        entry = bindings[name]
        fn = schema['functions'].get(name)
        notes = [(fn['category'] + '. ' if fn else '') + 'Standard REAPER API.']
        if entry['limitations']:
            notes.append(' '.join(entry['limitations']))
        if fn and entry['signatureHash'] == fn['signatureHash']:
            notes += [f"@returns {result_names(fn)}. Output order follows Lua.", f"@see {fn['documentation']}"]
            for p in entry['parameters']:
                if 'Float64Array' in p['type']:
                    notes += [f"@param {p['name']} Written back before resolution. Keep the same length while pending."]
                elif p['optional']:
                    notes += [f"@param {p['name']} Optional. Omit or pass null to keep a positional hole."]
        ts.append('  /**\n' + '\n'.join('   * ' + n.replace('*/', '* /').replace('\n', ' ').rstrip() for n in notes) + '\n   */')
        # Nullable optional slots match the runtime and preserve later argument positions.
        ts.append('  ' + signature(name, entry))
    ts.append('}')
    return {'runtime/reaper-api.generated.js': js, 'runtime/reaper-api.generated.d.ts': '\n'.join(ts) + '\n',
            'docs/api-reference.md': api_reference(schema, manifest)}


def verify(root, schema, manifest, check_generated=True):
    validate_schema(schema)
    validate_bindings(manifest)
    host_types = (root / 'runtime/reaper.d.ts').read_text(encoding='utf-8-sig')
    known_types = set(re.findall(r'\b(?:interface|type)\s+(\w+)', host_types))
    known_types.update(('string', 'number', 'boolean', 'null', 'undefined', 'void', 'unknown', 'true', 'false', 'Uint8Array', 'Float64Array'))
    for name, entry in manifest['functions'].items():
        for value in [entry['returns']] + [p['type'] for p in entry['parameters']]:
            if js_type_names(value) - known_types:
                raise ValueError(f'{name}: undeclared JavaScript type in {value}')
    pending = coverage(schema, manifest)['needsReview']
    if pending:
        raise ValueError('Native signature review required: ' + ', '.join(pending))
    # The independent ABI compiler must lower every native argument and Lua result.
    from tools.native_bindings import plans, manifest as native_manifest
    registered = [p['name'] for p in plans(schema)]
    if set(registered) != set(manifest['functions']) or manifest != native_manifest(schema):
        raise ValueError('Native compiler mappings do not match api/bindings.json. Review tools/native_bindings.py.')
    source = (root / 'src/core/core.cpp').read_text(encoding='utf-8-sig')
    if 'native_entries()' not in source or 'native_->invoke' not in source:
        raise ValueError('Native compiler registry is not connected to Bridge')
    direct = re.findall(r'\badd\("([A-Za-z_]\w*)"\s*,', source)
    if any(not name.startswith('ReaWeb') for name in direct):
        raise ValueError('Official APIs must use add_reaper, not the host API registry')
    if check_generated:
        for name, content in sdk_files(manifest, schema).items():
            path = root / name
            if not path.is_file() or path.read_text(encoding='utf-8') != content:
                raise ValueError(f'Stale generated SDK file: {name}. Run api_sync update --offline.')


def runtime_header(schema, manifest):
    count = coverage(schema, manifest)
    bindings = {}
    for name, entry in sorted(manifest['functions'].items()):
        bindings[name] = {'minArgs': sum(not p['optional'] for p in entry['parameters']),
                          'maxArgs': len(entry['parameters']), 'compatibility': entry['compatibility'],
                          'limitations': entry['limitations']}
    projection = {'schemaVersion': schema['schemaVersion'], 'reaperVersion': schema['source']['reaperVersion'],
                  'catalogueHash': schema['catalogueHash'],
                  **{key: count[key] for key in ('official', 'implemented', 'compatible', 'partial', 'missing')},
                  'bindings': bindings, 'knownMethods': sorted(schema['functions'])}
    data = encode(projection)
    if ')REAWEBAPI"' in data:
        raise ValueError('Invalid runtime projection delimiter')
    # MSVC limits each literal token. Adjacent short tokens form one static string.
    literals = '\n'.join('  value += R"REAWEBAPI(' + data[i:i + 2000] + ')REAWEBAPI";' for i in range(0, len(data), 2000))
    return '#pragma once\n#include <string>\nnamespace reaweb {\ninline const std::string api_schema_json = [] {\n  std::string value;\n' + literals + '\n  return value;\n}();\n}\n'


def write_files(files):
    """Stage all output first. Atomic per-file replacement, rollback on a write failure."""
    changed = {}
    for name, text in files.items():
        path, data = Path(name), text.encode('utf-8')
        # Git may check generated text out with CRLF on Windows. As in verify(),
        # line endings alone are not drift: preserve the original bytes and mtime.
        if path.is_file() and path.read_bytes().replace(b'\r\n', b'\n') == data.replace(b'\r\n', b'\n'):
            continue
        changed[path] = data
    staged, originals, replaced = {}, {}, []
    try:
        for path, data in changed.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            originals[path] = path.read_bytes() if path.exists() else None
            with tempfile.NamedTemporaryFile(dir=path.parent, prefix='.' + path.name + '.', suffix='.tmp', delete=False) as stream:
                staged[path] = Path(stream.name)
                stream.write(data)
                stream.flush()
                os.fsync(stream.fileno())
        for path, temporary in staged.items():
            os.replace(temporary, path)
            replaced.append(path)
    except OSError:
        for path in reversed(replaced):
            original = originals[path]
            if original is None:
                path.unlink(missing_ok=True)
            else:
                path.write_bytes(original)
        raise
    finally:
        for temporary in staged.values():
            temporary.unlink(missing_ok=True)
    return list(changed)


def report_text(report, full=False):
    c, d = report['coverage'], report['difference']
    lines = [f"REAPER API Mirror - {report['reaperVersion']}",
             f"Official: {c['official']} | Implemented: {c['implemented']} | Missing: {c['missing']}",
             f"Compatible: {c['compatible']} | Partial: {c['partial']} | Needs review: {len(c['needsReview'])}",
             f"Definitions: +{len(d['added'])} -{len(d['removed'])} changed {len(d['changed'])}"]
    if d['sourceChanged']:
        lines.append('Source metadata changed (version, format, origin or SHA-256).')
    if d['builtinsChanged']:
        lines.append('Excluded language builtin list changed.')
    for label, names in [('Added', d['added']), ('Removed', d['removed']), ('Needs review', c['needsReview'])]:
        if names:
            lines.extend(['', label + ':'] + ['- ' + n for n in names])
    for name, change in d['changed'].items():
        lines.extend(['', name + ': ' + ', '.join(change['fields']),
                      '  Before: ' + change['before']['lua'], '  After:  ' + change['after']['lua']])
        if 'native' in change['fields']:
            lines.extend(['  C before: ' + change['before']['c'], '  C after:  ' + change['after']['c']])
    if full:
        lines.extend(['', 'Coverage by category:'])
        lines.extend(f"- {name}: {value['implemented']}/{value['official']}" for name, value in c['categories'].items())
        lines.extend(['', 'Partial compatibility:'])
        lines.extend('- ' + n + ': ' + ' '.join(report['limitations'][n]) for n in c['partialNames'])
        lines.extend(['', 'Missing native bindings:'] + ['- ' + n for n in c['missingNames']])
    return '\n'.join(lines) + '\n'
