"""Generate data and declarations, never native implementations."""
import os
import re
import tempfile
from pathlib import Path
from .model import coverage, encode, validate_schema, validate_bindings, js_type_names


def sdk_files(manifest):
    bindings = manifest['functions']
    names = sorted(bindings)
    js = '// Generated by api_sync update. Do not edit.\nconst reawebApiMethods = Object.freeze(' + encode(names).rstrip() + ');\n'
    js += 'const reawebApiVoidMethods = Object.freeze(' + encode([n for n in names if bindings[n]['returns'] == 'void']).rstrip() + ');\n'
    ts = ['// Generated by api_sync update from api/bindings.json. Do not edit.',
          '// Only reviewed native bindings are declared here. See api/reaper_api.json for the catalogue.',
          'interface ReaWebAPI {']
    for name in names:
        entry = bindings[name]
        note = entry['compatibility'] + '. ' + ' '.join(entry['limitations'])
        ts.append('  /** ' + note.replace('*/', '* /').replace('\n', ' ') + ' */')
        params = ', '.join(p['name'] + ('?' if p['optional'] else '') + ': ' + p['type'] for p in entry['parameters'])
        ts.append(f"  {name}({params}): Promise<{entry['returns']}>;")
    ts.append('}')
    return {'runtime/reaper-api.generated.js': js, 'runtime/reaper-api.generated.d.ts': '\n'.join(ts) + '\n'}


def verify(root, schema, manifest, check_generated=True):
    validate_schema(schema)
    validate_bindings(manifest)
    host_types = (root / 'runtime/reaper.d.ts').read_text(encoding='utf-8-sig')
    known_types = set(re.findall(r'\b(?:interface|type)\s+(\w+)', host_types))
    known_types.update(('string', 'number', 'boolean', 'null', 'undefined', 'void', 'unknown', 'true', 'false', 'Uint8Array', 'Float64Array'))
    for name, entry in manifest['functions'].items():
        for value in [entry['returns']] + [p['type'] for p in entry['parameters']]:
            if js_type_names(value) - known_types:
                raise ValueError(f'{name}: undeclared JavaScript type in {value}')
    pending = coverage(schema, manifest)['needsReview']
    if pending:
        raise ValueError('Native signature review required: ' + ', '.join(pending))
    # The independent ABI compiler must lower every native argument and Lua result.
    from tools.native_bindings import plans, manifest as native_manifest
    registered = [p['name'] for p in plans(schema)]
    if set(registered) != set(manifest['functions']) or manifest != native_manifest(schema):
        raise ValueError('Native compiler mappings do not match api/bindings.json. Review tools/native_bindings.py.')
    source = (root / 'src/core.cpp').read_text(encoding='utf-8-sig')
    if 'native_entries()' not in source or 'native_->invoke' not in source:
        raise ValueError('Native compiler registry is not connected to Bridge')
    direct = re.findall(r'\badd\("([A-Za-z_]\w*)"\s*,', source)
    if any(not name.startswith('ReaWeb') for name in direct):
        raise ValueError('Official APIs must use add_reaper, not the host API registry')
    if check_generated:
        for name, content in sdk_files(manifest).items():
            path = root / name
            if not path.is_file() or path.read_text(encoding='utf-8') != content:
                raise ValueError(f'Stale generated SDK file: {name}. Run api_sync update --offline.')


def runtime_header(schema, manifest):
    count = coverage(schema, manifest)
    bindings = {}
    for name, entry in sorted(manifest['functions'].items()):
        bindings[name] = {'minArgs': sum(not p['optional'] for p in entry['parameters']),
                          'maxArgs': len(entry['parameters']), 'compatibility': entry['compatibility'],
                          'limitations': entry['limitations']}
    projection = {'schemaVersion': schema['schemaVersion'], 'reaperVersion': schema['source']['reaperVersion'],
                  'catalogueHash': schema['catalogueHash'],
                  **{key: count[key] for key in ('official', 'implemented', 'compatible', 'partial', 'missing')},
                  'bindings': bindings, 'knownMethods': sorted(schema['functions'])}
    data = encode(projection)
    if ')REAWEBAPI"' in data:
        raise ValueError('Invalid runtime projection delimiter')
    # MSVC limits each literal token. Adjacent short tokens form one static string.
    literals = '\n'.join('  value += R"REAWEBAPI(' + data[i:i + 2000] + ')REAWEBAPI";' for i in range(0, len(data), 2000))
    return '#pragma once\n#include <string>\nnamespace reaweb {\ninline const std::string api_schema_json = [] {\n  std::string value;\n' + literals + '\n  return value;\n}();\n}\n'


def write_files(files):
    """Stage all output first. Atomic per-file replacement, rollback on a write failure."""
    changed = {Path(p): text.encode('utf-8') for p, text in files.items()
               if not Path(p).is_file() or Path(p).read_bytes() != text.encode('utf-8')}
    staged, originals, replaced = {}, {}, []
    try:
        for path, data in changed.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            originals[path] = path.read_bytes() if path.exists() else None
            with tempfile.NamedTemporaryFile(dir=path.parent, prefix='.' + path.name + '.', suffix='.tmp', delete=False) as stream:
                staged[path] = Path(stream.name)
                stream.write(data)
                stream.flush()
                os.fsync(stream.fileno())
        for path, temporary in staged.items():
            os.replace(temporary, path)
            replaced.append(path)
    except OSError:
        for path in reversed(replaced):
            original = originals[path]
            if original is None:
                path.unlink(missing_ok=True)
            else:
                path.write_bytes(original)
        raise
    finally:
        for temporary in staged.values():
            temporary.unlink(missing_ok=True)
    return list(changed)


def report_text(report, full=False):
    c, d = report['coverage'], report['difference']
    lines = [f"REAPER API Mirror - {report['reaperVersion']}",
             f"Official: {c['official']} | Implemented: {c['implemented']} | Missing: {c['missing']}",
             f"Compatible: {c['compatible']} | Partial: {c['partial']} | Needs review: {len(c['needsReview'])}",
             f"Definitions: +{len(d['added'])} -{len(d['removed'])} changed {len(d['changed'])}"]
    if d['sourceChanged']:
        lines.append('Source metadata changed (version, format, origin or SHA-256).')
    if d['builtinsChanged']:
        lines.append('Excluded language builtin list changed.')
    for label, names in [('Added', d['added']), ('Removed', d['removed']), ('Needs review', c['needsReview'])]:
        if names:
            lines.extend(['', label + ':'] + ['- ' + n for n in names])
    for name, change in d['changed'].items():
        lines.extend(['', name + ': ' + ', '.join(change['fields']),
                      '  Before: ' + change['before']['lua'], '  After:  ' + change['after']['lua']])
        if 'native' in change['fields']:
            lines.extend(['  C before: ' + change['before']['c'], '  C after:  ' + change['after']['c']])
    if full:
        lines.extend(['', 'Coverage by category:'])
        lines.extend(f"- {name}: {value['implemented']}/{value['official']}" for name, value in c['categories'].items())
        lines.extend(['', 'Partial compatibility:'])
        lines.extend('- ' + n + ': ' + ' '.join(report['limitations'][n]) for n in c['partialNames'])
        lines.extend(['', 'Missing native bindings:'] + ['- ' + n for n in c['missingNames']])
    return '\n'.join(lines) + '\n'
