"""Input adapters. Never guess a signature that cannot be parsed."""
import hashlib
import html
import json
import re
from pathlib import Path
from urllib.request import Request, urlopen

OFFICIAL_URL = 'https://www.reaper.fm/sdk/reascript/reascripthelp.html'
MAX_BYTES = 16 * 1024 * 1024


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f'Duplicate JSON key: {key}')
        result[key] = value
    return result


def read_json(text):
    return json.loads(text, object_pairs_hook=unique_object,
                      parse_constant=lambda value: (_ for _ in ()).throw(ValueError(value)))


def plain(text):
    # The documentation sometimes joins a type's closing tag to its parameter.
    return ' '.join(html.unescape(re.sub(r'<[^>]+>', ' ', text)).split())


def parse_html(text):
    version = re.search(r'Generated by REAPER v([^<\s]+)', text)
    if not version:
        raise ValueError('HTML is missing the REAPER version marker')
    anchors = list(re.finditer(r'<a\s+name=["\']([^"\']+)["\'][^>]*>', text, re.I))
    functions, excluded, index = {}, [], None
    parsed_counts = {'c': 0, 'lua': 0}
    for i, anchor in enumerate(anchors):
        name = anchor[1]
        block = text[anchor.end():anchors[i + 1].start() if i + 1 < len(anchors) else len(text)]
        if name == 'function_list':
            index = re.findall(r'href=["\']#([^"\']+)["\']', block, re.I)
        signatures = {}
        for css, lang in [('c', 'c'), ('l', 'lua')]:
            items = re.findall(r'<div\s+class=["\']' + css + r'_func["\'][^>]*>\s*.*?<code>(.*?)</code>\s*.*?</div>', block, re.S | re.I)
            if len(items) > 1:
                raise ValueError(f'Duplicate {lang} signature: {name}')
            if items:
                signatures[lang] = plain(items[0])
                parsed_counts[lang] += 1
        if signatures:
            if name in functions or set(signatures) != {'c', 'lua'}:
                raise ValueError(f'Duplicate or incomplete standard API: {name}')
            # Track documentation changes without redistributing all upstream prose.
            description = re.sub(r'<div\s+class=["\'][celp]_func["\'].*?</div>', '', block, flags=re.S | re.I)
            functions[name] = {'signatures': signatures,
                               'documentationHash': hashlib.sha256(plain(description).encode()).hexdigest()}
        elif name.startswith(('lua_', 'eel_', 'python_')) and '<code>' in block:
            excluded.append(name)
    for css, lang in [('c', 'c'), ('l', 'lua')]:
        count = len(re.findall(r'<div\s+class=["\']' + css + r'_func["\']', text, re.I))
        if count != parsed_counts[lang]:
            raise ValueError(f'Unaccounted {lang} signature blocks: {count} vs {parsed_counts[lang]}')
    if index is None or len(set(index)) != len(index) or set(index) != set(functions):
        raise ValueError('Standard API index does not match parsed functions (possibly truncated HTML)')
    return version[1], functions, sorted(excluded)


def parse_markdown(text):
    """Explicit exchange format: version comment, ## Name, fenced c and lua signatures."""
    version = re.search(r'<!--\s*reaper-version:\s*([^\s]+)\s*-->', text)
    functions = {}
    sections = list(re.finditer(r'^## ([A-Za-z_]\w*)\s*$', text, re.M))
    for i, section in enumerate(sections):
        name = section[1]
        block = text[section.end():sections[i + 1].start() if i + 1 < len(sections) else len(text)]
        signatures = {}
        for lang, signature in re.findall(r'^```(c|lua)\s*\n(.*?)\n```\s*$', block, re.M | re.S):
            if lang in signatures:
                raise ValueError(f'Duplicate {lang} signature: {name}')
            signatures[lang] = ' '.join(signature.split())
        if name in functions or set(signatures) != {'c', 'lua'}:
            raise ValueError(f'Duplicate or incomplete Markdown API: {name}')
        functions[name] = {'signatures': signatures}
    return version[1] if version else None, functions, []


def load_source(location, source_format='auto', version=None, expected_hash=None):
    if expected_hash and not re.fullmatch(r'[0-9a-fA-F]{64}', expected_hash):
        raise ValueError('--sha256 requires 64 hexadecimal characters')
    if location.startswith('https://'):
        with urlopen(Request(location, headers={'User-Agent': 'ReaWebAPI-api-sync/1'}), timeout=30) as response:
            if not response.url.startswith('https://'):
                raise ValueError('Refusing HTTPS downgrade')
            data = response.read(MAX_BYTES + 1)
    elif '://' in location:
        raise ValueError('Use a local file or an HTTPS URL')
    else:
        with Path(location).open('rb') as stream:
            data = stream.read(MAX_BYTES + 1)
    if len(data) > MAX_BYTES:
        raise ValueError('API source exceeds 16 MiB')
    digest = hashlib.sha256(data).hexdigest()
    if expected_hash and digest != expected_hash.lower():
        raise ValueError('Source SHA-256 does not match --sha256')
    text = data.decode('utf-8-sig')
    if source_format == 'auto':
        source_format = 'json' if text.lstrip().startswith('{') else 'html' if re.search(r'<html\b', text, re.I) else 'markdown'
    if source_format == 'html':
        detected, functions, excluded = parse_html(text)
    elif source_format == 'markdown':
        detected, functions, excluded = parse_markdown(text)
    else:
        obj = read_json(text)
        detected = obj.get('reaperVersion', obj.get('source', {}).get('reaperVersion'))
        functions = obj.get('functions')
        excluded = obj.get('excludedBuiltins', [])
    if version and detected and version != detected:
        raise ValueError(f'--source-version {version} disagrees with source {detected}')
    version = detected or version
    if not version or not re.fullmatch(r'\d+\.\d+[A-Za-z0-9.+_-]*', version):
        raise ValueError('A valid REAPER version is required (use --source-version for unversioned imports)')
    if not isinstance(functions, dict) or not functions:
        raise ValueError('Source contains no API functions')
    if not isinstance(excluded, list) or any(not isinstance(x, str) for x in excluded):
        raise ValueError('Invalid excludedBuiltins')
    # Local absolute paths would make the committed schema machine-specific.
    origin = location if location.startswith('https://') else Path(location).name
    source = {'format': source_format, 'origin': origin, 'documentation': OFFICIAL_URL,
              'reaperVersion': version, 'sha256': digest,
              'scope': 'standard-reascript-c-lua'}
    return source, functions, sorted(set(excluded))
